### ISSUE TITLE
internal link from forms leads to 404

### ISSUE THREAD

**Issue by unco** [canonical/canonical.com#1004]
[hr forms](https://forms.canonical.com/hr/) has a menu item that leads to https://canonical.com/enterprise-services -> 404

**Comment by carkod** [comment]
Scheduled https://warthogs.atlassian.net/browse/WD-5751?atlOrigin=eyJpIjoiMDEwYjVjZjU0ZDZhNDAyMWJkNjA2ZTY2ZDBjMDNhOTUiLCJwIjoiaiJ9
