### ISSUE TITLE
Unable to access my Candidate page on your website.

### ISSUE THREAD

**Issue by realOKK** [canonical/canonical.com#1020]
The link to access my candidate page for a UX Designer position sent to my email Okechi.kkevin@live.com could not be accessed.
Here is a report to that effect seeking for the issue to be resolved as I look forward to the next stage of my interview process - Interviews and a project management challenge.
Thank you for your time and consideration in this matter.

Sincerely
Kenechi Kevin OKECHI

**Comment by anthonydillon** [comment]
This issue has been resolved and communication continued via email.
