### ISSUE TITLE
[careers] searching with "field engineer" doesn't show all field engineering positions

### ISSUE THREAD

**Issue by nobuto-m** [canonical/canonical.com#1022]
The following search returns 9 roles as of today.
https://canonical.com/careers/all?search=field+engineer

However, the result doesn't include the following positions as Field *Software* Engineer.
- Field Software Engineer - EMEA https://canonical.com/careers/2404732
- Field Software Engineer - APAC https://canonical.com/careers/5137653

**Comment by carkod** [comment]
@juanruitina was this included in the work Liza did?

**Comment by juanruitina** [comment]
@carkod No, this hasn't been address yet.

**Comment by lizzochek** [comment]
Hello @nobuto-m. Currently the search does show the one for APAC, you may try searching for it on the page. As the one for EMEA was deleted, it is not shown in the search. If you believe that the issue still happens for you, please reopen the issue and provide more details
