### ISSUE TITLE
Header breaks on cadidate's application page 

### ISSUE THREAD

**Issue by akbarkz** [canonical/canonical.com#1024]
When you are on cadidate's application page (/careers/application/<id>) click on Careers section in the header. It will show items horizontally instead of vertically, unlike on any other page. Leave the Careers section open and click on Products section. The Careers section will not close and remain open together with Products. Also, the chevron icons do not show correctly. 
Here are the screenshots:
<img width="1159" alt="Screen Shot 2023-08-25 at 08 59 32" src="https://github.com/canonical/canonical.com/assets/15943863/829874a6-8c20-4d5f-a91d-bae1151604db">
<img width="1382" alt="Screen Shot 2023-08-25 at 08 59 43" src="https://github.com/canonical/canonical.com/assets/15943863/484caee7-c845-4bee-be95-e2cd3c47d645">

**Comment by anthonydillon** [comment]
Hi @akbarkz, thank you for taking the time to report this issue to us. This task has been scheduled for maintenance shortly.

**Comment by haideralipunjabi** [comment]
Is this still pending? Can this be assigned to me?
