### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by scaul91** [canonical/canonical.com#1027]
I have tried several times to submit an application for HR job and each time return with an error "Bad Request. The browser (or proxy) sent a request that this server could not understand."

Please assist. thank you.

**Comment by anthonydillon** [comment]
I believe this issue has now been rectified @mtruj013?

**Comment by mtruj013** [comment]
Yes, fixed in https://github.com/canonical/canonical.com/pull/1029. Closing
