### ISSUE TITLE
Candidate Page - File a bug

### ISSUE THREAD

**Issue by amyev514** [canonical/canonical.com#1061]
401: Unauthorised

**Comment by akbarkz** [comment]
@amyev514 Can you please check the link that you were provided? Does it look like this: `https://canonical.com/careers/application/<ID of your application>`?

**Comment by akbarkz** [comment]
@amyev514 This was a temporary issue with URL that leads to the candidate's page not including applicant ID. This issue has been fixed and in your next letters from Canonical you will be receiving a working link. But if you need it now, please reach out to your Hiring Lead and request.
Please re-open the issue if the problem still remains. And please provide more details.
