### ISSUE TITLE
linux application installation issue 

### ISSUE THREAD

**Issue by musammatsamina** [canonical/canonical.com#1069]
![PSX_20230826_181741](https://github.com/canonical/canonical.com/assets/1865625/7c8bd699-df5b-4da5-95d2-93cb991e133a)

**Comment by akbarkz** [comment]
@musammatsamina Can you please describe better what exactly is this issue about?

**Comment by akbarkz** [comment]
Closing since the ticket description is not clear. Feel free to re-open it again once you add more details in the description.
