### ISSUE TITLE
Cookies keeps  Popping up.

### ISSUE THREAD

**Issue by Honestyohue** [canonical/canonical.com#1070]
I notice that the cookies keep popping up even after the user accept it.. if that same users enter another page on the website the cookies will still pop up..

**Comment by akbarkz** [comment]
@Honestyohue The cookies message appears on different domains. If you accepted it once on `canonical.com` it will not appear again on this domain unless you explicitly clear your cookies. But on `canonical.com` we have links to other websites, such as `ubuntu.com` or `juju.is`, and that is the reason you see cookies message popping up again.

**Comment by Honestyohue** [comment]
Thank you for your response.. ok I get it all now.
