### ISSUE TITLE
401 unauthorized error when accessing candidate page

### ISSUE THREAD

**Issue by cdnyyzyul** [canonical/canonical.com#1076]
I am a candidate applying a position at Canonical. The Hiring Lead has communicated with me the following in email: 

We would also like to share the link for you to access your [Candidate Page](https://canonical.com/careers/application/). Here you will be able to track your progress through our interview stages.....

Problem:
Following the provided link, I get 401 Unauthorized error. 

I have already notified the lead via email.

**Comment by akbarkz** [comment]
@cdnyyzyul Looks like you were provided a broken link. The proper link should point to `https://canonical.com/careers/application/<ID of your application>`. In your case `<ID of your application>` is missing.
So, yes, please contact your Hiring Lead and ask to check the link.

**Comment by akbarkz** [comment]
@Josh1313 This was a temporary issue with URL that leads to the candidate's page not including applicant ID. This issue has been fixed and in your next letters from Canonical you will be receiving a working link. 
Good that we have already reached out to your Hiring Lead as he/she can send you an updated working link right away.
