### ISSUE TITLE
Candidate page link broken

### ISSUE THREAD

**Issue by Josh1313** [canonical/canonical.com#1077]
The candidate page link is broken.Unauthorized
You do not have access to this page.
You can File a bug if this is an error.

**Comment by akbarkz** [comment]
@Josh1313 there are already two issues open with the same problem. Can you check the link itself?
The proper link should point to `https://canonical.com/careers/application/<ID of your application>`. Do you have the <ID of your application> there?.

**Comment by akbarkz** [comment]
@Josh1313 This was a temporary issue with URL that leads to the candidate's page not including applicant ID. This issue has been fixed and in your next letters from Canonical you will be receiving a working link. But if you need it now, please reach out to your Hiring Lead and request.
