### ISSUE TITLE
Cannot apply for job role

### ISSUE THREAD

**Issue by OGsiji** [canonical/canonical.com#1083]
I spent my time applying for job roles and they are rejected.   
 Cannot apply for job role

**Comment by anthonydillon** [comment]
@OGsiji is the application process not working or are you referring to being rejected at application review?

**Comment by anthonydillon** [comment]
I am seeing no recent errors in the logs. Could you try again and let me know if you hit the same issue?

**Comment by OGsiji** [comment]
Okay, I have applied and submitted my resume.
Thank you.
 My email is ogunniransiji@gmail.com. I have heard great things about canonical and I can't wait to be part of the team.
