### ISSUE TITLE
Canonical Candidate Page -Error

### ISSUE THREAD

**Issue by Mwitch1** [canonical/canonical.com#1096]
Good afternoon,
     I've tried to access the Canonical Candidate Page located here: https://canonical.com/careers/application/ .  I was given this link to track progress through the interviewing stages.  Would you be able to assist in granting me access or know what I might do so that I don't receive the error?

Thank you so much,
Mae Witcher
mae.witcher@gmail.com

**Comment by JoannaCoPo** [comment]
In case this is a larger issue, I'll add that I am also getting an error at the link for my Candidate Page, a `500 Server error`.  I had access last week week (roughly Oct. 23-26th) and first encountered the error today. The Hiring Lead for my page is `Ivo Jansky`.

Thanks and cheers!

**Comment by raul-f** [comment]
I am also getting a `500 Server error` on my candidate page. I checked earlier today - about 6 hours ago - and it was working as usual.

Thanks,
Raul F.

**Comment by bluster** [comment]
I am seeing this issue on my candidate page today.

Thanks,
Brendan L.

**Comment by maubuz** [comment]
Same here. 500 error accessing my candidate page.

**Comment by anthonydillon** [comment]
Sorry we have an API issue which has just been resolved.
