### ISSUE TITLE
Resume could not be submitted

### ISSUE THREAD

**Issue by abhishekjindal1** [canonical/canonical.com#1107]
The page is throwing 500 internal server error

**Comment by akbarkz** [comment]
@abhishekjindal1 Can you please provide a screenshot or a link to a position to which you were trying to apply?

**Comment by abhishekjindal1** [comment]
https://canonical.com/careers/5143074

I tried applying for this position, but unfortunately after spending a lot
of time it gave the error message. Then I tried to reload the page, and
tried to submit the application with minimum effort ( not sure if it will
work again) but it was successful this time. 😪

**Comment by anthonydillon** [comment]
Sorry about that but we have limits on the size and format. We will add these notes to the application. I am glad you could apply in the end.
