### ISSUE TITLE
Continuous cookie permissions requests

### ISSUE THREAD

**Issue by vjd3** [canonical/canonical.com#1110]
Every product page onto which I clicked asked me to confirm my cookie preferences. I am not working with a guest or private account and I am accepting cookies every time. And yet, it continues to ask.

**Comment by akbarkz** [comment]
@vjd3 that's because different products open different websites. On canonical.com we have links to other websites such as microk8s.io, maas.io, juju.is, ubuntu.com.

**Comment by lizzochek** [comment]
@vjd3 we believe the behaviour is expected as each product has a separate website. If you believe this is not correct and you stayed within one website, please open a new issue and fill the template with more information. Thank you
