### ISSUE TITLE
Cannot access the Kubernetes announcment blog posts

### ISSUE THREAD

**Issue by perk** [canonical/canonical.com#1122]
Hi!

First blog post `Canonical﻿ Kubernetes 1.24 is now generally available` on [this blog page](https://canonical.com/blog/author/achalkias) doesn't work, it links to:
https://canonical.com/blog/canonical%ef%bb%bf-kubernetes-1-24-is-now-generally-available

Additionally [this page has the same problem](https://canonical.com/blog/author/yalton): the  `Canonical﻿ Kubernetes 1.28 is now generally available` blog post link is broken, it goes to:
https://canonical.com/blog/canonical%ef%bb%bf-kubernetes-1-28-is-now-generally-available

**Comment by anthonydillon** [comment]
This is now working with a change to title and slug in the blog admin.
