### ISSUE TITLE
Application webpage Server Error

### ISSUE THREAD

**Issue by JacobLiefeld** [canonical/canonical.com#1133]
The webpage my recruiter mailed me regarding Canonical's hiring process seems to be down.

https://canonical.com/careers/application/gAAAAABlOXVnS9Cmgj8u8EEr72UWZSLWS33mpzMGyhZwYWpM8RWLHCUfSPyiFJrfgi1odXWyt45dqvSt99eKIIz39n5E21Av6g==

<img width="639" alt="image" src="https://github.com/canonical/canonical.com/assets/29663672/ec6c1023-9a53-4c06-99f7-de39f0f0841f">

**Comment by MGuyadeen01** [comment]
+1

**Comment by anthonydillon** [comment]
Sorry we have an API issue which has just been resolved.
