### ISSUE TITLE
Contact in link!!

### ISSUE THREAD

**Issue by waranagi1973** [canonical/canonical.com#1141]
**I think it would be a good idea to attach each letter in the contact information part as a link!!**

**Comment by carkod** [comment]
Hi @waranagi1973. Thanks for reporting this.

What contact information are you talking about? Can you provide a link, a screenshot and any further details you may consider relevant? Thank you.

**Comment by lizzochek** [comment]
Hello @waranagi1973 . Thank you for opening an issue. If your proposal is still relevant, please open a new issue and provide more details
