### ISSUE TITLE
422 error when applying for job

### ISSUE THREAD

**Issue by thatSteveFan** [canonical/canonical.com#1144]
When trying to apply for a job, I get a 422 error

## Process

Went to https://canonical.com/careers/5151903, went to apply, filled out information and hit "Submit"

## Current and expected result

I got sent back to the job posting with a banner saying "Error 422: Unprocessable Entity. Please try again! "

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/16244692/20ae1fc9-22d3-41f8-b29f-c8ef528e1c4f)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

THIS SEEMS TO BE BROKEN, I only get some spam site

**Comment by petesfrench** [comment]
Hi @thatSteveFan, can you share more details of the the environment this occurred in i.e. operating system, browser, etc. I am unable to replicate this on my machine.

**Comment by thatSteveFan** [comment]
Hi Petes,

I managed to apply today when using Chrome. Looks like there might be some firefox issues.  I was using firefox 120.0. Not sure if this is something you want to fix, or maybe just suggest chrome somewhere.

I am on windows 10 if that matters, but I suspect not.

Is there a dummy job application I can use to test? Don't want to accidentally spam and have my actual application get rejected.

**Comment by petesfrench** [comment]
Hey @thatSteveFan, 

I have been able to replicate the issue even on firefox.

Can you check any attached documents are in an allowed format, these are:
.pdf, .doc, .docx, .txt, .rtf

I will have a colleague running Windows to take a look at this.

You could run fill in the form with dummy information. We typically use 'test' for all the values as this will automatically be filtered out.

Thanks, 
Pete

**Comment by lizzochek** [comment]
Hey @thatSteveFan ! We were not able to reproduce the issue on either of the operational systems. I was also not able to catch any errors through network log. It may be an occasional error on the Greenhouse API. Please try again and if the issue persists for you, reopen this issue.
