### ISSUE TITLE
Career descriptions used to have the requisition ID attached to the content

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#1149]
The reason this is useful is that it can be difficult to associate a job role with a requisition in Greenhouse. As so we [added the requisition ID](https://github.com/canonical/canonical.com/blob/main/webapp/greenhouse.py#L63-L72) to the bottom of the description to provide discoverability.  

Since the change to [Fix application job post id #1100](https://github.com/canonical/canonical.com/pull/1100) we have [stopped using the Vacancy class](https://github.com/canonical/canonical.com/pull/1100/files#diff-55f12a9f17b4ba61d3e37852150b7d78b8aedbe3629bc4ce8173d4b572297a54R266-R267) to render the job details. The Vacancy class is where [the add the additional content we added](https://github.com/canonical/canonical.com/blob/main/webapp/greenhouse.py#L104).

I understand that this change was made to provide the active status of a role but we should find a way to combine this information within the Vacancy class to ensure consistent data usage across the site.

**Comment by carkod** [comment]
Completed with https://github.com/canonical/canonical.com/pull/1260. Let us know if there are still any issues
