### ISSUE TITLE
Fix "Show more" button

### ISSUE THREAD

**Issue by roysatadru** [canonical/canonical.com#1151]
Accessing the https://canonical.com/careers/application/<id> page, there is a button named "Show more" which should ideally expand the contents of "Hiring lead" but it is not doing that. It is expanded from the start, i.e., there are no expansion happening once "Show more" button is clicked because there is nothing to expand. So we should show a trimmed content in the beginning and show the entire content on clicking on "Show more" button.

**Comment by anthonydillon** [comment]
Thank for taking the time to report this issue to use @roysatadru. I'll look into it.

**Comment by anthonydillon** [comment]
I have fixed the content which was causing the issue. Thank you again.
