### ISSUE TITLE
Application Page not Loading

### ISSUE THREAD

**Issue by andrescastro1100100** [canonical/canonical.com#1157]
As I'm following my application process, it seems like my personal application page won't load.

Link: https://canonical.com/careers/application/gAAAAABlg3W0TlYVhTUonLuvxbBLuBxOh_41BoJU6t-tVcFvb2jNm8oJ0Uk5tZ9_VnmH8jsivY3YK6x0iP9_DjajqGT5mWPO2w==

**Comment by drednout** [comment]
I also see the problem on my application page, long loading and finally - 500th.

**Comment by andrescastro1100100** [comment]
It seems to be working for me now! Might want to check it out.

**Comment by drednout** [comment]
It also works for me now. This is fine! :)
