### ISSUE TITLE
Misclicking a link on careers dropdown navigation closes the navigation

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical.com#1160]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary

How the careers dropdown navigation currently functions, if you miss click a link and click the background of the navigation, it closes.
Maybe this is the intended behavior, but personally I found it annoying and un-intuitive 

## Process

Go to https://canonical.com/ on a large screen
Open the careers dropdown navigation
Click anywhere (that isn't a link)

**Comment by carkod** [comment]
Yes, it's intended. The whole navigation of canonical.com may need a UX revision, it doesn't make much sense to have that large meganav for just career and a tiny one for the rest.

**Comment by akbarkz** [comment]
@juanruitina shall I tackle this issue and improve it?

**Comment by juanruitina** [comment]
This is indeed awkward. Clicking on the meganav background shouldn't close it. However, clicking on the transparent overlay below it (the one that covers the whole page when the meganav is open) _should_ close the meganav though. This would be consistent with the meganav in Ubuntu.com

**Comment by immortalcodes** [comment]
Hi @petesfrench ,
This issue should be fixed after you are done with the new nav for canonical.com?

**Comment by petesfrench** [comment]
@immortalcodes correct. This can be closed.
