### ISSUE TITLE
Add a valid favicon to the website 

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#1161]
It looks bad on us to have broken favicons when people search for Canonical and our products. Can you please update the favicon with one that is compliant with Google search?

![image](https://github.com/canonical/canonical.com/assets/1413534/ae103285-cfa1-4e34-9d28-1459afb059ad)

**Comment by carkod** [comment]
I don't know if @akbarkz or @bartaz one of them is working on this, you may want to link to this issue to close it after merging.

**Comment by akbarkz** [comment]
I'm on it, will update this issue as soon as it's resolved.
