### ISSUE TITLE
Company page 404

### ISSUE THREAD

**Issue by Cyrannosaurus** [canonical/canonical.com#1164]
Clicked on the "Company" tab button and got a 404

<img width="1170" alt="image" src="https://github.com/canonical/canonical.com/assets/70718730/4858fae0-2a54-449c-9969-e9ae1ec6d523">

**Comment by carkod** [comment]
Thanks @Cyrannosaurus for reporting this. There is no company page, it should be dropdown, can you provide more information as requested in the Issue template? 
<img width="848" alt="Screenshot 2024-02-09 at 12 08 55" src="https://github.com/canonical/canonical.com/assets/14939793/87ae0071-f2fe-47cb-9d34-5cce57dc1c04">

**Comment by akbarkz** [comment]
Closing as there is not enough details to investigate upon
