### ISSUE TITLE
Candidate Page 404

### ISSUE THREAD

**Issue by r41k0u** [canonical/canonical.com#1176]
## Summary

Trying to access the candidate page now leads to a 404 error.

## Process

Navigate to https://canonical.com/careers/application/{candidate-token} where {candidate-token} is the token for my application. Open to sharing it privately to the assignees.

## Current and expected result

Current result: 404 page
Expected Result: Candidate page - I am in the process

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/76248539/fa997dc7-bceb-4148-a286-3ce9a61929a7)

## Browser details

Microsoft Edge Version 123.0.2380.1 (Official build) stable app, dev channel (64-bit)

**Comment by akbarkz** [comment]
@r41k0u Looks like you were trying to open an application page for which you had been rejected. It shows 404 after 2 days of rejection. I reached out to your hiring lead and he confirmed that you were notified of the rejection.
I see you have another open application at Canonical for another position, maybe you were trying to open that application page? Please find the link to it in the corresponding email, it opens fine.
