### ISSUE TITLE
Careers form might be broken

### ISSUE THREAD

**Issue by radhesh1** [canonical/canonical.com#1186]
The careers page sends the wrong job mail if you apply for one job and then gives answers for a different job.

**Comment by akbarkz** [comment]
@radhesh1 Can you please provide more details? With screenshots if possible.

**Comment by radhesh1** [comment]
I have only the screenshots of the emails that I have received.
sorry for the late reply.

**Comment by lizzochek** [comment]
Hello @radhesh1. Thank you for filing an issue. to replicate it we need more detail. If it keeps happening for you, please file a new issue with screenshots and application link (if possible)
