### ISSUE TITLE
Cannot Submit Application

### ISSUE THREAD

**Issue by ahmedskhalil** [canonical/canonical.com#1191]
## Summary

Cannot submit an application through the website

## Steps to reproduce the behavior

After filling all the required fields, clicking submit yields a 500 server error regardless of browser or device. 

## Expected behavior

Submission successful with confirmation Email. 

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/29197392/fb3feb3a-0efc-4675-8e91-c1f5d9dd46a6)

## Browser/device details

- Device: iOS, macOS
- Browser: Chrome, Opera

**Comment by lizzochek** [comment]
Hello @ahmedskhalil. Thank you for filling an issue. Could you please specify which application you were filing? Preferably send a link or the position number you can find in the link (canonical.com/careers/{number} )

**Comment by lizzochek** [comment]
@ahmedskhalil currently submission works fine on our end, if it doesn't work for you, please open a new issue filling the template with more details, thank you
