### ISSUE TITLE
Inability to Add Education or School name not on the list 

### ISSUE THREAD

**Issue by udoc1** [canonical/canonical.com#1196]
## Summary

Whenever I try Applying for a Job through the GreenHouse.io platform, i have difficulty inputting my Education and Course, especially because it is not on the list.
I would suggest you give users the ability to Type the information they intend to add.

## Steps to reproduce the behavior

1. Go to (https://boards.greenhouse.io/canonicaljobs/jobs/5774499?gh_src=fda0c7061us#app)
2. Click on 'School and Discipline'
3. Try Selecting my School (Enugu State University of Science and Technology) or a Discipline like User Interface Design Specialization, or Project Management. or try selecting Coursera

## Expected behavior

I want to be able to input my school manually if it is not in the list, or even input my Discipline manually if it is not in the drop down

## Screenshot
![Screenshot 2024-03-04 140813](https://github.com/canonical/canonical.com/assets/97223010/21769c58-1adb-46e9-9ad1-5a865c14472d)

- Device: [Laptop]
- OS: [e.g. Windows 11]
- Browser [Chromei]

**Comment by lizzochek** [comment]
Hello @udoc1, thank you for filing an issue. Unfortunately this input is controlled by Greenhouse, not us, therefore we can't add manual input. However, we made this field not required
