### ISSUE TITLE
Candidate Page not available 

### ISSUE THREAD

**Issue by gbe001** [canonical/canonical.com#1197]
According to received documentation from Hiring Lead the page should have been accessible for 48 hours staring from
 Wed, Mar 6, 12:45 PM.
However the page is not available and I need to request the report for the GIA test.
Thanks for your support
KR
![image](https://github.com/canonical/canonical.com/assets/162562497/419ee8dc-8c6a-46d6-a071-0db6c4e4b893)

**Comment by lizzochek** [comment]
Hello @gbe001. Thank you for filing an issue. Most probably you have been rejected or applied to another position. If you didn't receive any information on that matter, please ask your hiring lead to confirm the status of your application.
