### ISSUE TITLE
application candidate page link is giving 404

### ISSUE THREAD

**Issue by KojaksHubbyToBe** [canonical/canonical.com#1200]
Dear team, I'd need your help! 
I got a link to my candidate application page which is now .giving me 404 error :(

[https://canonical.com/careers/application/gAAAAABl1PxcljbL6C_wvFBLmxYZzlGi_pk6gSKuBjbPaM8hbui91vckJaqKs4z2D-6bE2Nt33qy4nwGFmmkoFYiRqYd2jEhvA==](url)

Now, the link is no longer working and now it could either mean that my application to canonical is no longer active (I'd be in freeze shock state) or it's just a technical issue. The latter would mean: I hope you can fix at a glance :)
It worked on Friday (08-MAR-2024).

So maybe you might not be able to help me in the application itself, but solving the technical topic would help me tracking my application progress (and hopefully I can join the canonical crew :)
Thank you for looking into the issue,
kind regards
Any
![error_screenshot](https://github.com/canonical/canonical.com/assets/163013566/2f7c7c00-1d60-42ca-ae33-d88b312a1d3c)
a

**Comment by lizzochek** [comment]
Hello @KojaksHubbyToBe. Most probably you have been rejected or applied to the other position. Thank you for filing an issue

**Comment by shreyshah117** [comment]
How did you got link to your candidate application page. I have given my pyschometric assessments but still haven't received any mail regarding candidate status page
