### ISSUE TITLE
Submitting Application Error

### ISSUE THREAD

**Issue by Johnfgeorge100** [canonical/canonical.com#1209]
HI Team,

I am trying to submit my application but an error keeps appearing. 500 server issue 

![image](https://github.com/canonical/canonical.com/assets/163329577/9ab0d6b4-ec15-4a88-95bf-5aec66d82876)

Please let me know what I can do

Kind regards
John

**Comment by lizzochek** [comment]
Hello @Johnfgeorge100, thank you for filing an issue. Could you provide more details to replicate the issue? Which position are you trying to submit an application for? Are you getting a 500 after submitting the form or when accessing the application page?

**Comment by lizzochek** [comment]
@Johnfgeorge100 the issue is not happening on my side currently. If it keeps happening for you, please reopen the issue
