### ISSUE TITLE
unable to access candidate account

### ISSUE THREAD

**Issue by Djerba74** [canonical/canonical.com#1233]
Hi,

While trying to reach my candidate account, I have a 404 return code error message.
Could you please help with this ?

Many thanks

**Comment by lizzochek** [comment]
Hello @Djerba74 
Please provide us with more context on your issue. Were you rejected? Did you apply for another position? Did the page work for you before? Did you get any updates on your application status via email?
Thank you.

**Comment by Djerba74** [comment]
Hi Liza,

I received an email from Regis Paquette on March 30th  informing me that I have been shortlisted for written interview. I did the necessary and uploaded my document assessment using the following link. https://app.greenhouse.io/tests/75eaf3c342855eff46ec72b493e4da9f?utm_medium=email&utm_source=TakeHomeTest&utm_source=Automated<https://app.greenhouse.io/tests/75eaf3c342855eff46ec72b493e4da9f?utm_medium=email&utm_source=TakeHomeTest&utm_source=Automated>

 But when it comes to checking my application update using the following link, I have got an error message inaccessible.
<https://canonical.com/careers/application/gAAAAABmBdxziuNFzDaYgPqnmjE69X14x-xLzy8Y2Wxpvcto-CKvVi1RmutZNqAAXhgc3NlePtcQcjwOz4cyy5pw5uxYZkhtQQ==>
protection.outlook.com<https://canonical.com/careers/application/gAAAAABmBdxziuNFzDaYgPqnmjE69X14x-xLzy8Y2Wxpvcto-CKvVi1RmutZNqAAXhgc3NlePtcQcjwOz4cyy5pw5uxYZkhtQQ==>
[X]<https://canonical.com/careers/application/gAAAAABmBdxziuNFzDaYgPqnmjE69X14x-xLzy8Y2Wxpvcto-CKvVi1RmutZNqAAXhgc3NlePtcQcjwOz4cyy5pw5uxYZkhtQQ==>

Thanks for your help.

Adel Ben Ouirane

Le 24 avr. 2024 à 10:51, Liza ***@***.***> a écrit :

﻿

Hello @Djerba74<https://github.com/Djerba74>
Please provide us with more context on your issue. Were you rejected? Did you apply for another position? Did the page work for you before? Did you get any updates on your application status via email?
Thank you.

**Comment by lizzochek** [comment]
Hello @Djerba74. Sorry to inform you that your page is unaccessible because you were rejected. Thank you for filing an issue.
