### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Natasja1** [canonical/canonical.com#1234]
Hello,

I recently applied to a role at Canonical and tried to log in today to track the progress of my application, unfortunately this page could not be found.  Could you please assist in my log in.

Thank you.

Natasja G 

<img width="1265" alt="Screenshot 2024-04-02 at 08 48 29" src="https://github.com/canonical/canonical.com/assets/165767703/e3705ad3-a736-4a09-96e0-f7bc6f212f60">

**Comment by lizzochek** [comment]
Hello @Natasja1 
Please provide us with more context on your issue. Were you rejected? Did you apply for another position? Did the page work for you before? Did you get any updates on your application status via email? 
Thank you.

**Comment by akbarkz** [comment]
You normally receive 404 after 2 days after your application has been rejected. Please check your inbox for the rejection email.
