### ISSUE TITLE
Home page navigation vs careers navigation

### ISSUE THREAD

**Issue by bartaz** [canonical/canonical.com#124]
Found on https://staging.canonical.com/

Canonical.com main page navigation looks and behaves differently from /careers nav:

canonical.com:
<img width="1189" alt="Screenshot 2019-12-19 at 16 46 18" src="https://user-images.githubusercontent.com/83575/71187352-3266a480-227f-11ea-85a4-b95a1b0a8f55.png">

canonical.com/careers:
<img width="1214" alt="Screenshot 2019-12-19 at 16 46 05" src="https://user-images.githubusercontent.com/83575/71187366-38f51c00-227f-11ea-9c27-cbe9f3b9bcad.png">

Both navs look a bit different (different hover state) and the same items of navigation do different things on both pages:

It's weird that 'Careers' on main page just scrolls the page to relevant section, but when you are in /careers section it's a link to /careers page.
Also there is no way to get to /careers page from home page. "Explore career" button links directly to /careers/start.

Products dropdown is only on /careers, but not on home page.

Also there seems to be an issue with home page navigation on small screens:
<img width="423" alt="Screenshot 2019-12-19 at 16 49 40" src="https://user-images.githubusercontent.com/83575/71187601-a86b0b80-227f-11ea-8ff6-2ec868e60605.png">

<img width="426" alt="Screenshot 2019-12-19 at 16 49 51" src="https://user-images.githubusercontent.com/83575/71187611-af921980-227f-11ea-8f37-1859d5d80950.png">

**Comment by carkod** [comment]
@petesfrench any idea which should be the correct behavior? /careers or /#careers?

**Comment by davegoddard42** [comment]
@carkod this is fixed in the new navigation and homepage refresh. I'll add it to that Epic and we can close it once the site relaunches?
