### ISSUE TITLE
Bug in Career Explorer Page

### ISSUE THREAD

**Issue by erincayaz** [canonical/canonical.com#1249]
## Summary

In the [career explorer](https://canonical.com/careers/career-explorer) page, after selecting 5 options from the list and clicking Submit Choices, I am directed to a new page and it is working like a charm. However, when I go back, my selections are reset to default at the top, but the checkboxes are not cleared.

## Steps to reproduce the behavior

1. Go to [Career Explorer](https://canonical.com/careers/career-explorer)
2. Select 5 choices from the list
3. Click **Submit choices**
4. Go back to previous page
5. See that selections on top are cleared but the options are not:

![Screenshot 2024-05-02 at 23 13 14](https://github.com/canonical/canonical.com/assets/45971992/231b6d45-0d14-4f21-94de-760722600843)

I can make selections when these items are selected, which is problematic as well:

![Screenshot 2024-05-02 at 23 15 45](https://github.com/canonical/canonical.com/assets/45971992/afdc4d8e-eb6a-4d5c-984c-6c48f88fdc17)

## Expected behavior

I believe there are two ways to approach this: One is to clear options at the bottom as well; the other is to leave both choices as they were.

## Browser/device details

- Device: Macbook Pro
- OS: MacOS
- Browser Google Chrome
- Version 124.0.6367.94

**Comment by lizzochek** [comment]
Hello @erincayaz. thank you for filing an issue. I can't replicate it.  Does it still happen to you?

**Comment by erincayaz** [comment]
Hi, I can't replicate as well. I believe it is fixed, thanks, have a nice day
