### ISSUE TITLE
About 

### ISSUE THREAD

**Issue by chanchalv18** [canonical/canonical.com#1252]
About Canonical

At Canonical, we believe in the transformative power of open-source software to drive innovation, collaboration, and progress. As the company behind Ubuntu, one of the world's most widely used Linux distributions, we are dedicated to creating a more open and accessible digital future for all.

Our Mission

Our mission is to enable individuals and organizations to harness the full potential of open-source technology. We are committed to developing and supporting software that empowers people to innovate, collaborate, and build a better world together.

Our Values

At Canonical, our values guide everything we do:

Innovation: We are committed to pushing the boundaries of what's possible through continuous innovation and experimentation.
Collaboration: We believe in the power of collaboration and teamwork to drive positive change and achieve shared goals.
Inclusivity: We are dedicated to creating an inclusive and welcoming environment where everyone's contributions are valued and respected.
Integrity: We operate with honesty, transparency, and integrity in all our interactions and decisions.
Excellence: We strive for excellence in everything we do, setting high standards for ourselves and delivering exceptional results.
Our Expertise

With over two decades of experience in the open-source ecosystem, Canonical is a recognized leader in Linux and cloud computing. Our team of experts is passionate about creating innovative solutions that empower individuals and organizations to succeed in a digital-first world.

Key Milestones

Since our founding in 2004, Canonical has achieved several key milestones:

Launch of Ubuntu, the world's most popular Linux distribution
Introduction of Ubuntu Server and Ubuntu Core for cloud and IoT deployments
Development of Juju, MAAS, and other tools for cloud orchestration and management
Expansion of our global footprint with offices and contributors around the world
Meet Our Team

Our leadership team brings together a diverse group of talented individuals with expertise in technology, business, and open-source advocacy. Meet the people driving innovation and leading the way at Canonical.

**Comment by chanchalv18** [comment]
I don't see any About page for the company hence suggested this

**Comment by carkod** [comment]
@chanchalv18 hi. What are you suggesting here? Can you be more explicit?

**Comment by carkod** [comment]
Stale. Feel free to reopen if you have more details.
