### ISSUE TITLE
Remove Right Chevron SCSS (Upstreamed in Vanilla 4.12.0)

### ISSUE THREAD

**Issue by jmuzina** [canonical/canonical.com#1269]
c.com is creating its own right chevron style here:

https://github.com/canonical/canonical.com/blob/d3db0d7047e26e032c495e366ee0589b191a425c/static/sass/styles.scss#L644-L649

However as of Vanilla 4.12.0, this class has been [upstreamed](https://vanillaframework.io/docs/patterns/icons). This style can be removed after [updating Vanilla to 4.12.0](https://github.com/canonical/canonical.com/pull/1268). 

The [career progression page](https://canonical.com/careers/company-culture/progression) also uses left and right chevrons in the carousel:

https://github.com/canonical/canonical.com/blob/d3db0d7047e26e032c495e366ee0589b191a425c/static/sass/_pattern_careers-progression.scss#L246-L264

The `transform:rotate` rules can be removed from `p-careers-progression-carousel__previous` and `p-careers-progression-carousel__next`, and those styles should now extend `.p-icon--chevron-left` and `.p-icon--chevron-right`, respectively.

**Comment by britneywwc** [comment]
Hi @jmuzina, is this still blocked by Vanilla?

**Comment by jmuzina** [comment]
Hi @britneywwc ! No, this is in Vanilla now and is not blocked
