### ISSUE TITLE
I've tried to submit a application for a graduate PM position, instead of sending it, I recieved a page 404 not found.

### ISSUE THREAD

**Issue by justthatpixel** [canonical/canonical.com#1271]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

## Browser/device details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by carkod** [comment]
Thanks for reporting this. Can you still find the application page? If not most likely this job is closed. Feel free to reopen if you have more information about the application page link
