### ISSUE TITLE
Candidate Page showing 404 error

### ISSUE THREAD

**Issue by Austen1998** [canonical/canonical.com#1278]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

I am currenting interviewing for a role in Canonical. May I know why am I seeing this and can't access my page? 
I would like to be able to track my application progress and be notified on my status so I would be appreciative if this issue can be resolved as I have not received any email on my end in my inbox.

Thanks in advance,
Any

## Expected behavior

Able to see tracking process

## Screenshot

![image](https://github.com/canonical/canonical.com/assets/32379295/5647b80b-aed1-49fe-aaef-db89c8a12af6)

## Browser/device details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by akbarkz** [comment]
@Austen1998 Usually 404 is shown after 2 days from the moment the application was rejected. Or if your application has been moved to another position. In both cases you should have received a notification email specifying that change in your application.
Have you received a letter from Canonical about the rejection or transfer? If not, it could be possible that the hiring lead forgot to send it to you. In that case I would suggest contacting him/her directly and checking the status of your application.
I will close this issue for now, but feel free to re-open it after you check your email and/or hear back from your hiring lead.
