### ISSUE TITLE
Misspelled words

### ISSUE THREAD

**Issue by jgr1zzly** [canonical/canonical.com#1318]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]
On your cover page when people log on, twice whoever wrote it up has misspelled organization and organized. They spelled both words with an "s"
## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

**Comment by immortalcodes** [comment]
Hi,
Do you mean we have "organised" on out site while it should be "organized"?
Both the spellings are correct, the difference is that "organised" is primarily used in British English while the latter is used in American English, we follow British English for the spellings on our sites.
Please provide more information if you meant something else with the link to the page.
Thanks
