### ISSUE TITLE
Candidate page 404 error

### ISSUE THREAD

**Issue by KCDeeksha** [canonical/canonical.com#1323]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

**Comment by immortalcodes** [comment]
I am closing this for now, but if you are still facing this issue feel free to re-open it.
Thanks
