### ISSUE TITLE
Even though I have received the credentials to login for the website, its showing not access

### ISSUE THREAD

**Issue by Lingaraju-m** [canonical/canonical.com#1327]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

**Comment by immortalcodes** [comment]
Hi,
Thanks for reporting. Could you please elaborate more on this issue?

**Comment by immortalcodes** [comment]
Hi,
More information could have been helpful.
Some of the access could be restricted but if you think that this was something that should have been accessible, feel free to re-open the issue.
Thanks
