### ISSUE TITLE
Error while sending a job application

### ISSUE THREAD

**Issue by DenisKardakov** [canonical/canonical.com#1333]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

I was filing a job application for Global Head of Sales - Finance Services Industry, once I hit sent i got a 404 error - page not found

## Steps to reproduce the behavior

1. Go to canonical.com -> careers -> sales-> Global Head of Sales - Finance Services Industry
2. File an application
3. Hit sent 

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

I cannot since the page has already been closed

## Browser/device details

- Device Mac M1 2020
- OS: sonoma 14.5
- Browser safari
- Version 17.5

**Comment by lizzochek** [comment]
Hello @DenisKardakov, thank you for filing an issue, please follow this issue for updates on your problem: https://github.com/canonical/canonical.com/issues/1356
