### ISSUE TITLE
https://hackerassociate.com/contact-us/#:~:text=%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B8%96%E0%B8%B2%E0%B8%A1%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%99%E0%B8%B5%E0%B9%89,%E0%B8%95%E0%B8%B2%E0%B8%A1%0A%E0%B9%80%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%B2

### ISSUE THREAD

**Issue by Chanchaichoochuay007** [canonical/canonical.com#1350]
[*Note](`url`) - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

## Browser/device details

https://hackerassociate.com/contact-us/#:~:text=%E0%B8%AA%E0%B8%AD%E0%B8%9A%E0%B8%96%E0%B8%B2%E0%B8%A1%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B8%99%E0%B8%B5%E0%B9%89,%E0%B8%95%E0%B8%B2%E0%B8%A1%0A%E0%B9%80%E0%B8%A3%E0%B8%B2%E0%B8%A1%E0%B8%B2

**Comment by mtruj013** [comment]
@Chanchaichoochuay007 closing this as no bug was described
