### ISSUE TITLE
Bug while submitting my application

### ISSUE THREAD

**Issue by AfonsoSCCarvalho** [canonical/canonical.com#1356]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

I have tried to submit three times my application for the jobpost at:
https://canonical.com/careers/6151796/application

Each time I pressed submit (after writing all my responses) it crasched with a 404 error.

I managed to solve it by applying by Linkedin.

## Steps to reproduce the behavior

1. Go to (https://canonical.com/careers/6151796/application)
2. Fill every field.
3. Click on Submit application
4. 404 error

## Expected behavior

I expected to submit my application and get some kind of confirming feedback. 

## Screenshot

![image](https://github.com/user-attachments/assets/89877ee6-64a7-4733-806e-3f92e561d46d)

## Browser/device details

- Device: ROG Strix
- OS: Windows 11
- Browser Google Chrome and also tried it in Explorer

**Comment by lizzochek** [comment]
Hello @AfonsoSCCarvalho thank you for filing an issue. The application link itself gives a 404 at the moment. We are currently investigating this and will get back to you as soon as we are able to locate the issue

**Comment by AfonsoSCCarvalho** [comment]
No problem at all! I am following the recruitment process through other
possible means. Thank you for your response!

Best regards,
Afonso

Liza ***@***.***> escreveu (terça, 10/09/2024 à(s) 14:20):

**Comment by lizzochek** [comment]
@AfonsoSCCarvalho I have contacted the team and they clarified that the application has been deleted. Whenever job posts information is updated in greenhouse - careers page won't update immediately. GET requests which display job posts are hitting the cache server while POST request submitting application is hitting flask application and greenhouse APIs. So this does take some time for the application to be removed at all. This is done for quicker performance of the website.
The team is investigating whether we can improve the process. Thank you again for bringing that up!

**Comment by lizzochek** [comment]
Hello @AfonsoSCCarvalho. Our team is currently investigating what possible issues may happen for the applications. Unfortunately, we can't check your exact application as it has been deleted some time before. If you need any more assistance, please reopen the issue. Thank you for drawing our attention to this :)
