### ISSUE TITLE
Link doesnit work

### ISSUE THREAD

**Issue by Fasithahamed12** [canonical/canonical.com#1439]
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

[Please describe the issue.]

## Expected behavior

[A clear and concise description of what you expected to happen.]

## Screenshot

[Please include a screenshot.]

**Comment by Fasithahamed12** [comment]
so backend will be error

**Comment by samhotep** [comment]
Hey @Fasithahamed12 could you please add more context to the form?

**Comment by britneywwc** [comment]
Closing this ticket due to lack of information and inactivity. Feel free to reopen with more context of the issue.
