### ISSUE TITLE
The circle of products should lead to the product pages or to the description below

### ISSUE THREAD

**Issue by grebennikov** [canonical/canonical.com#168]
The first glance to the circle of elements on the right of the main page naturally makes you think that each icon should be active and leads you somewhere, or at least have some kind of a pop-up with description.

**Comment by sumanbiswas7** [comment]
Since it is an image separate links could not be added to each icon. I could add some animations and maybe one link that leads somewhere.

**Comment by sumanbiswas7** [comment]
@grebennikov Since it is an image separate links could not be added to each icon. I could add some animations and maybe one link that leads somewhere.
