### ISSUE TITLE
Move partners feed client-side

### ISSUE THREAD

**Issue by nottrobin** [canonical/canonical.com#196]
Loading the homepage is quite slow 'cos it loads many partners feeds. This is not terrible as we have caching, but every now and then a user will experience a load much slower than necessary.

Really things like the partners feed should be client-side, as they're non-essential.

**Comment by anthonydillon** [comment]
It would appear, the partner logos are now hard coded. Ok to close this one in that case?

**Comment by carkod** [comment]
As Ant mentioned, we don't need to move client-side?

**Comment by nottrobin** [comment]
It looks to me like the API call is still being made in the index view, so the homepage still has a back-end dependency on the partners API, which is the bit I wanted to avoid:

https://github.com/canonical/canonical.com/blob/a9692f68c0a09079abaa9d23969a8e07a2bd8902/webapp/app.py#L45
