### ISSUE TITLE
Fieldset styling inconsistent with defualt vanilla fieldset

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/canonical.com#371]
Current:

![image](https://user-images.githubusercontent.com/2741678/112498091-1b660a80-8d7e-11eb-9df2-2ad61b45bff8.png)

Expected:

![image](https://user-images.githubusercontent.com/2741678/112498118-21f48200-8d7e-11eb-8e08-e982aa3c48b6.png)

[Vanilla default](https://vanillaframework.io/docs/examples/base/forms/fieldset)

**Comment by tbille** [comment]
This section is currently fully being redesigned and rewritten. Closing the issue.
