### ISSUE TITLE
Dead link in Landscape docs

### ISSUE THREAD

**Issue by hwittenborn** [canonical/canonical.com#380]
https://landscape.canonical.com/static/doc/user-guide/ch01.html

In the `Ubuntu Advantage` paragraph, the `legal assurance` link appears to be broken.

**Comment by hwittenborn** [comment]
Just checked out of curiosity - looks like every link in the paragraph is broken.

**Comment by sowasred2012** [comment]
This is related to #433, we need some more redirects.

**Comment by petesfrench** [comment]
@pmahnke could you tell us where these links should redirect to on caonical.com?

**Comment by davegoddard42** [comment]
@pmahnke Just a reminder

**Comment by joeljose350** [comment]
I can fix a few of the broken links on that paragraph and open a pull request, but I can't find the repository of that website. Can someone send a link to the repository please?

**Comment by joeljose350** [comment]
I can fix a few of those broken links but I can't find this page in the [landscape-docs repo](https://github.com/canonical-web-and-design/landscape-docs). So if someone can send a link to the source code of that page, I would love to open a pull request fixing some of those broken links.

**Comment by cristinadresch** [comment]
@pmahnke to add notes to what we should do about these links

**Comment by carkod** [comment]
Maybe @simpoir do you have an idea where is this page located in the repo?

**Comment by simpoir** [comment]
That would be the static docs copy in the landscape-server itself, [on launchpad](https://bugs.launchpad.net/landscape/+bug/1791434).
Those static pages are outdated enough they might be worth pruning and linking to docs.ubuntu.com (assuming that's still the documentation platform of choice)

**Comment by carkod** [comment]
Stale and I believe this is not relevant anymore with new [landscape docs](https://ubuntu.com/landscape/docs)

Feel free to reopen if issue persists.
