### ISSUE TITLE
Formatting issue on partner-portal.canonical on small screens

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical.com#481]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary

The cards displayed on the page do not respond as expected on small screens

## Process

- Go to [partner-portal.canonical.com](partner-portal.canonical.com)
- Reduce screen size past the break-point of small screens

## Current and expected result

- The second card is a different size and not inline with the one above

- You expect them to be inline and the same size with some spacing between

## Screenshot

![image](https://user-images.githubusercontent.com/58276363/150361036-1ef4791a-1970-4740-82b1-df884c96eef4.png)

**Comment by sumanbiswas7** [comment]
@petesfrench seems like the https://partner-portal.canonical.com/ page is not a part of this repository.

**Comment by petesfrench** [comment]
Hey @sumanbiswas7, this repo for partner-portal.canonical isn't host openly on github so I thought this would be the next best place to file the issue. I am happy to delete it from here and file it in a more appropriate place

**Comment by anthonydillon** [comment]
Let's remove it and try and find the correct place to report this issue or just use Jira.
