### ISSUE TITLE
p-inline-list--middot rendering wrong on careers navigation

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical.com#482]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary

p-inline-list--middot rendering wrong on careers navigation, where the dots are not centered

## Process

- Go to canonical.com
- Navigate to careers and open the navigation
- Look at the bottom for a list of bullet point separated links

## Current and expected result

Currently, the dots are not centered and they should be

## Screenshot

![image](https://user-images.githubusercontent.com/58276363/150362442-9c7a5c9d-d0ac-40b3-a457-f6ddf5c5f613.png)

**Comment by carkod** [comment]
Looks fixed now? https://canonical.com/careers/
