### ISSUE TITLE
link to certification site on IHV and OEM Programme is broken

### ISSUE THREAD

**Issue by bladernr** [canonical/canonical.com#509]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary

On the [IHV and OEM Programme partner page](https://canonical.com/partners/ihv-and-oem) there is a link in the section called "Increase your sales by becoming Ubuntu Certified" that points to the certification page.:

the link is:
[Learn more about Ubuntu certified hardware](https://certification.ubuntu.com/certification)

this triggers a redirect that is broken.  The redirect url becomes:

https://ubuntu.com/certified/certification

which returns a 404.  

## Process
1: Go to above OEM Program link
2: Scroll to the Learn More link and click it
3: ???
4: PROFIT! (Or fail on a 404, actually)

## Current and expected result

This should, instead, successfully link to https://ubuntu.com/certified/

The fix should just be to correct that link to directly point to https://ubuntu.com/certified/ rather than depend on the redirect.

## Screenshot

This is the section in question:
![Screenshot from 2022-03-29 13-52-24](https://user-images.githubusercontent.com/4295496/160674801-37ee0439-b0a3-4088-a6f7-a8e6f605be70.png)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by sowasred2012** [comment]
Thanks for reporting this @bladernr, this is being addressed in https://github.com/canonical-web-and-design/canonical.com/pull/511
