### ISSUE TITLE
[UX] Partners page secondary nav is not optimised for mobile

### ISSUE THREAD

**Issue by davegoddard42** [canonical/canonical.com#598]
The Partners pages' secondary nav on canonical.com features many links, these are all displayed, with wrapping used to make them fit. This means about 45% of the screen is taken up by the menu.

![image](https://user-images.githubusercontent.com/25453620/181364039-a9e3ccaf-e0b4-491a-bdf6-beef066090ae.png)

**Comment by davegoddard42** [comment]
@wgx - I didn't manage to look at this before leaving sorry.

**Comment by sowasred2012** [comment]
This is resolved with the new nav
