### ISSUE TITLE
[c.c application page] Create copy doc for candidate page

### ISSUE THREAD

**Issue by marinacastejon** [canonical/canonical.com#601]
[Copy doc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit#heading=h.oies5asn2qqj)

**Comment by sowasred2012** [comment]
LGTM - with so many possible states it's going to be an unusual copy doc, but it works. The only change I made was to move the copy doc to /careers and rename the file as "/application/<token>"
