### ISSUE TITLE
webapp/../templates/partial/_footer.html in top-level template code error

### ISSUE THREAD

**Issue by carkod** [canonical/canonical.com#610]
We are having loads of Sentry reporting a weird template error https://sentry.is.canonical.com/canonical/canonical-com/issues/27890/?query=is%3Aunresolved

**Comment by sowasred2012** [comment]
Looks like something is making a request to /content/..;/crx/packmgr/service.jsp;  - what is that? https://sentry.is.canonical.com/canonical/canonical-com/issues/27890/#breadcrumbs

84% of the 10.4k instances of the error are from the same user...

**Comment by minkyngkm** [comment]
@nottrobin could you take a look at this please?

**Comment by carkod** [comment]
Try debugging this with docker

**Comment by carkod** [comment]
Doesn't seem to be happening anymore
