### ISSUE TITLE
Wrong navigation selected onload of page

### ISSUE THREAD

**Issue by tbille** [canonical/canonical.com#635]
- Go on: https://canonical.com/practice/documentation
- On a bigger screen when I land on the page, sometimes the 4 pillars sections is selected sometimes the introduction. (see gif, I keep reloading and I am getting different selection each time)

![ll4Ot4bvqm](https://user-images.githubusercontent.com/2707508/191957313-2115c112-b928-4cc3-912f-d162516beb5d.gif)

## Expected behaviour 

 If no anchor in the URL, the introduction should always be selected on load of the page.

**Comment by petesfrench** [comment]
I have been unable to replicate this problem on chrome or firefox. 

However, I did notice some bugging behavior when scrolling on this page. It is is inconsistently updating the side navigation.

**Comment by tbille** [comment]
I just tried. And replicated it on the first load of the page :scream:
