### ISSUE TITLE
[c.c. application page] Update copy

### ISSUE THREAD

**Issue by marinacastejon** [canonical/canonical.com#642]
Update copy as per stakeholder's feedback. Updated sections highlighted in yellow in the [copy doc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit#).

**Comment by marinacastejon** [comment]
@sowasred2012 new issue that need to be prioritised soon. It's a dev issue FYI.

**Comment by petesfrench** [comment]
Closing as this is addressed in by the issue reference here
