### ISSUE TITLE
[c.c. application page] Update profile section

### ISSUE THREAD

**Issue by marinacastejon** [canonical/canonical.com#645]
Update the profile section based on the updated mock-ups for the visual design. Use [this section in the specs](https://docs.google.com/document/d/1aENPmLdPjoRtMgmmGX2x4iewevRv905OdkKgqqm-sHk/edit#bookmark=id.4c2wishvowu8) as the source of truth for the structure.

**Comment by marinacastejon** [comment]
@sowasred2012 another dev issue to prioritise

**Comment by marinacastejon** [comment]
@lyubomir-popov whenever the figma mock-ups are ready please add the link here, thanks

**Comment by marinacastejon** [comment]
@petesfrench pending visual mock-ups

**Comment by marinacastejon** [comment]
@petesfrench please use [this section in the specs](https://docs.google.com/document/d/1aENPmLdPjoRtMgmmGX2x4iewevRv905OdkKgqqm-sHk/edit#bookmark=id.4c2wishvowu8)  as the source of truth for the structure, there are not mock-ups for all cases.

**Comment by petesfrench** [comment]
@marinacastejon Are we still waiting on a visual design for this? Or do you want to build it based on the layout described in the doc?

**Comment by petesfrench** [comment]
@marinacastejon @lyubomir-popov  Thank you, I think I understand so will start on this now. Will follow up with anything I am not sure about.
