### ISSUE TITLE
Ubuntu, MAAS and Launchpad logos are out of date in the /projects page

### ISSUE THREAD

**Issue by fitojb** [canonical/canonical.com#646]
Also, the logos are all surrounded by an inset squircle, which were part of Matthieu James-developed visual language from the Ubuntu Phone days (🥲), so you may want to update that as well.

**Comment by petesfrench** [comment]
@spencerbygraves The logos on this page don't use standard logos, but have been edited to include a rounded border. How do we want to go about replacing outdated ones? see https://canonical.com/projects

**Comment by carkod** [comment]
@lyubomir-popov can you take a look at this when you've got time?

**Comment by fitojb** [comment]
No outdated logos anymore.
