### ISSUE TITLE
https://canonical.com/intellectual-property-policy not found

### ISSUE THREAD

**Issue by toabctl** [canonical/canonical.com#647]
In the cloud-images streams files (eg. https://cloud-images.ubuntu.com/minimal/releases/streams/v1/com.ubuntu.cloud:released:download.json) we set the license to http://www.canonical.com/intellectual-property-policy but this just gives a 404. Is there another path we should use?

**Comment by carkod** [comment]
I believe the right page should be https://ubuntu.com/legal/intellectual-property-policy

**Comment by carkod** [comment]
@toabctl can you update this?

**Comment by toabctl** [comment]
> @toabctl can you update this?

yes, I can

**Comment by carkod** [comment]
@toabctl have you been able to update this?

**Comment by toabctl** [comment]
working on it now. but feel free to close this ticket here.
