### ISSUE TITLE
[c.c. application page] replace the hiring_leads.json file with the directory API

### ISSUE THREAD

**Issue by goulinkh** [canonical/canonical.com#653]
The [Directory API](https://directory.wpe.internal/graphql/) is live and working now (through VPN, we might need to ask IS to allow connection from web k8s cluster to the WPE k8s cluster), information that the Directory API provide, live data for:
- employee's name
- image base64
- employee's title: this one is specified in the prototype that Marina did but isn't present currently on the page because we were waiting for the directory API to be live

**Comment by carkod** [comment]
Superseded by https://warthogs.atlassian.net/browse/WD-1554
