### ISSUE TITLE
[https://canonical.com/#products] Fix a typo

### ISSUE THREAD

**Issue by tanyahmaunga274** [canonical/canonical.com#669]
Add a double quote at the end of the statement indicated in the screenshot.
![Screenshot from 2022-10-22 10-37-18](https://user-images.githubusercontent.com/72440426/197329948-31da5a29-7a9a-4ecb-aefb-df8f7eb26dab.png)
[Screencast from 22-10-2022 10:53:46.webm](https://user-images.githubusercontent.com/72440426/197330638-1377efb1-8230-4ed2-90ae-fa31b76816f4.webm)

**Comment by sowasred2012** [comment]
Thanks for reporting - we'll look into this. For dev: the double quote is there, but it disappears below the x-large breakpoint.
