### ISSUE TITLE
Extend the careers search to more then the title 

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#681]
The job search should search the skills and job descriptions as well as the title.

**Comment by sowasred2012** [comment]
The search plugin we use is currently setup to match against title, description and department - we should just need to add skills to [this list](https://github.com/canonical/canonical.com/blob/main/templates/careers/_search.html#L70), and verify that it works (`'skills'` is an array, whereas the other values are strings, so I'm not 100% certain if/how the plugin handles those).
