### ISSUE TITLE
"Show all" button in open roles list at careers does nothing

### ISSUE THREAD

**Issue by nobuto-m** [canonical/canonical.com#682]
https://canonical.com/careers/all?search=sales

As of writing, there are 29 roles open with a keyword "sales" and the first 20 results are shown. However, clicking "Show all" button does nothing. Looks like the button doesn't have any registered event.

https://canonical.com/careers/all?search=sales
![Screenshot from 2022-11-09 22-07-42](https://user-images.githubusercontent.com/4356209/200838982-9963ae83-f119-4581-8afd-76b26a78b7d5.png)

^^^ no event registered, and clicking the button does nothing.

https://canonical.com/careers/all?search=engineer
![Screenshot from 2022-11-09 22-07-16](https://user-images.githubusercontent.com/4356209/200839050-d2c5e2f0-d198-4824-b2b5-42b294d78ff2.png)

^^^ there is a registered event and the button works as expected.

**Comment by sowasred2012** [comment]
Thanks for reporting, we'll fix this ASAP
