### ISSUE TITLE
Other application title is visible when they are all expired

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#689]
The section 'THE STATUS OF YOUR OTHER APPLICATIONS' is rendered even when there are no other applications, at the assessment stage
![image](https://user-images.githubusercontent.com/58276363/202138017-c3ec46ca-f149-4b47-a67e-b663e8c729ec.png)

**Comment by sowasred2012** [comment]
@anthonydillon I'm not totally sure how to look at a test candidate page, is this issue still valid or was it addressed in a recent change?

**Comment by anthonydillon** [comment]
@sowasred2012 yes this is still an issue. The issue here is that the UI hides applications that are closed but only in the template so the condition to check if there are any others `other_applicaiton.count() > 0` is true but nothing is rendered.

**Comment by britneywwc** [comment]
Hi, thanks for raising this issue. I spoke to @muhammadbassiony and this seems to be an old issue so will be closing this for now. Feel free to reopen if the issue persists.
