### ISSUE TITLE
the CANONICAL logo is hard up against the top instead of centered vertically

### ISSUE THREAD

**Issue by minkyngkm** [canonical/canonical.com#694]
Issue reported from MM [channel](https://chat.canonical.com/canonical/pl/94h4n4g9mtfa7fp1nzwhocmnye)

## Summary

the CANONICAL logo is hard up against the top instead of centred vertically within the black header. These only happen on phone-size screens / narrow window widths.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/57550290/203044047-83ab5d6f-8d18-4b56-b77a-895b35621ad5.png">

This one seems to be vanilla issue. [Issue](https://github.com/canonical/vanilla-framework/issues/4608) has been filed after talking with Bartek

**Comment by sowasred2012** [comment]
Fixed by https://github.com/canonical/canonical.com/pull/700
