### ISSUE TITLE
Link to "Products" in main navigation is broken

### ISSUE THREAD

**Issue by juanruitina** [canonical/canonical.com#696]
The "Products" link in the top navigation, which is an internal link pointing to "#products", seems broken. It should scroll to the Products section in the middle of the page.

Possible cause: both the Products section _and_ the navigation list item that contains the link have "products" as id. Given that it is placed before the products section, no scroll happens.

## Screenshot

![Screenshot 2022-11-24 at 15 22 18](https://user-images.githubusercontent.com/1409729/203806966-b279bd53-7d32-43c9-920d-e8941f015022.png)

![Screenshot 2022-11-24 at 15 28 14](https://user-images.githubusercontent.com/1409729/203808098-4020e140-0829-4971-a117-0fd42d225000.png)

## Browser details

Chrome on Mac

**Comment by sowasred2012** [comment]
There are two elements with the same "#products" id, one is the nav item, and the other is the products section - we should update the id of the products section to something unique and link to that.
