### ISSUE TITLE
Job role id is null for some applications

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#698]
## Summary
There are cases when the job role id is null. This is if the candidate doesn't apply and they are referred. 
We should not rely on this field for rendering the application page

## Process
- Open [this link](https://pastebin.canonical.com/p/qvsk2QY7Ss/) and visit the candidate
- Visit there application page in custom application fields
- See 500

**Comment by goulinkh** [comment]
Fixing the not relying on this field (`job_post_id` is the missing field) will result in using the job title, see this commit for more details: https://github.com/canonical/canonical.com/commit/667762521959d04a08c54433116ab2eaadf61b91

**Comment by goulinkh** [comment]
Another option is to use the tile of the job post when available and default to the job title otherwise.

**Comment by andesol** [comment]
@goulinkh We've been looking at the same issue. I think using job name when the other one is not available is ok

**Comment by anthonydillon** [comment]
Yeah seems a reasonable compromise
