### ISSUE TITLE
Careers finder returns 500 error

### ISSUE THREAD

**Issue by lenevdm** [canonical/canonical.com#709]
When submitting options on the Careers Finder page a 500 error happens.  https://canonical.com/careers/results?core-skills=Analyzer,Helper,Teacher,Stalwart,Contributor

**Comment by sowasred2012** [comment]
Thanks for reporting this @lenevdm, we'll fix this asap.

For dev: we are seeing a [number of errors arise in Sentry](https://sentry.is.canonical.com/canonical/canonical-com/issues/29923/?query=is%3Aunresolved) from `sorted__departments` not being defined, causing this 500.

**Comment by carkod** [comment]
I think [my PR](https://github.com/canonical/canonical.com/pull/710) actually fixed all of them. Seems to be working.
