### ISSUE TITLE
status.canonical.com green

### ISSUE THREAD

**Issue by sdarwin** [canonical/canonical.com#714]
This morning "apt-get update" is very very slow.  Tested from multiple locations and many CI jobs.  At least AWS Ohio and Hetzner Germany.   Simply frozen after 20 minutes. 

```
>>>>> APT: UPDATE...
...
Get:14 http://security.ubuntu.com/ubuntu bionic-security amd64 Contents (deb) [204 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages [1328 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic amd64 Contents (deb) [39.5 MB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security i386 Contents (deb) [115 MB]
Get:18 http://archive.ubuntu.com/ubuntu bionic i386 Contents (deb) [38.8 MB]
```

https://status.canonical.com says "All components are Operational" is all green. It could be an enhancement to capture this sort of information and report a network issue at status.canonical.com

**Comment by sowasred2012** [comment]
@xnox could you help us get this to the right person? We're not sure who maintains status.c.c

**Comment by xnox** [comment]
> @xnox could you help us get this to the right person? We're not sure who maintains status.c.c

But not on a public forum.

**Comment by nottrobin** [comment]
No idea if this is still an issue, but regardless this is not an issue with the canonical.com website.

If this still still an issue, please refile it by following the instructions at https://help.ubuntu.com/stable/ubuntu-help/report-ubuntu-bug.html.en.
