### ISSUE TITLE
500 errors returned from pagination in blog archive

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#716]
## Summary

Filtering the blog by month results is a 500.

## Process

If you visit https://canonical.com/blog/archives the page loads but if you filter by a previous month. Such as; https://canonical.com/blog/archives?year=2019&month=5. The result is a 500.

There are many Sentry errors reported.

## Current and expected result

Should render a filtered list of posts to that month.

**Comment by sowasred2012** [comment]
The `month_name` view helper method is missing (I suspect this a copy/paste issue, from the blog being ported over from u.c https://sentry.is.canonical.com/canonical/canonical-com/issues/26895/?query=is%3Aunresolved)
