### ISSUE TITLE
Applied to a job on your website but got 500: Server error after submission

### ISSUE THREAD

**Issue by flowac** [canonical/canonical.com#726]
I have applied to this one with extensions disabled on Firefox 107.0.1 on Windows 11 Pro. I have accepted to all cookies.
Same issue using Microsoft Edge 108.0.1462.46
https://canonical.com/careers/3821346

**Comment by olalekanteeblaze** [comment]
I'm also experiencing this issue

**Comment by valerio-bozzolan** [comment]
I think  this is a related problem:

https://github.com/canonical/canonical.com/issues/730

**Comment by anthonydillon** [comment]
The fix has landed and the careers section all working again.
