### ISSUE TITLE
Cannot search by keyword, error 500

### ISSUE THREAD

**Issue by mariusfilip** [canonical/canonical.com#727]
When I search jobs by a keyword, I get:

"500: Server error
Something’s gone wrong.

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-web-and-design/canonical.com/issues). If not, please [file a new issue](https://github.com/canonical-web-and-design/canonical.com/issues/new)."

**Comment by gorohoroh** [comment]
There's also a 500 when navigating to most [job openings referenced here](https://canonical.com/careers/all), such as:
* https://canonical.com/careers/3039369
* https://canonical.com/careers/3779936
* https://canonical.com/careers/2587303
* https://canonical.com/careers/4187039
* https://canonical.com/careers/3295491
* https://canonical.com/careers/3821346
* https://canonical.com/careers/3756791

**Comment by flowac** [comment]
Meanwhile you can search for the same jobs on linkedin and apply there. I had to do this yesterday because the canonical site showed 500 after submission.

**Comment by anthonydillon** [comment]
@mariusfilip thank you for taking the time to let us know about this issue. I fix has been proposed and should be live shortly.

**Comment by anthonydillon** [comment]
The fix has landed and the careers section all working again.
