### ISSUE TITLE
Canonical Jobs Matrix not working

### ISSUE THREAD

**Issue by dcpope** [canonical/canonical.com#730]
https://canonical.com/careers/results?core-skills=Developer,Helper,Fixer,Teacher,Mentor returns a 500 error

**Comment by valerio-bozzolan** [comment]
I can reproduce with different URLs. Random one:

https://canonical.com/careers/results?core-skills=Developer,Fixer,Helper,Problem%20Solver,Contributor

**Comment by anthonydillon** [comment]
@dcpope thank you for taking the time to let us know about this issue. I fix has been proposed and should be live shortly.

**Comment by anthonydillon** [comment]
The fix has landed and the careers section all working again.

**Comment by dcpope** [comment]
Thank you!

 

David Pope
