### ISSUE TITLE
Regarding https://canonical.com/careers/2878179

### ISSUE THREAD

**Issue by LinuxGalaxyGold** [canonical/canonical.com#731]
When I try to apply for the role, I get this message:

500: Server error
Something’s gone wrong.

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-web-and-design/canonical.com/issues). If not, please [file a new issue](https://github.com/canonical-web-and-design/canonical.com/issues/new).

I have strong interest in applying, thank you kindly for your assistance,

Anthony

**Comment by ianpmcguire** [comment]
Facing the same issue here.

**Comment by anthonydillon** [comment]
@LinuxGalaxyGold thank you for taking the time to let us know about this issue. I fix has been proposed and should be live shortly.

**Comment by anthonydillon** [comment]
The fix has landed and the careers section all working again.
