### ISSUE TITLE
Can't apply to https://canonical.com/careers/3447034

### ISSUE THREAD

**Issue by sconger** [canonical/canonical.com#732]
Simply generates an error when pressing submit application

500: Server error
Something’s gone wrong.

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-web-and-design/canonical.com/issues). If not, please [file a new issue](https://github.com/canonical-web-and-design/canonical.com/issues/new).

Some of the other engineering jobs also error, so the jobs site may just be generally broken.

**Comment by anthonydillon** [comment]
@sconger thank you for taking the time to let us know about this issue. I fix has been proposed and should be live shortly.

**Comment by sconger** [comment]
Looks like it's happy now:
Congratulations! Your application to our Senior Web Developer - Workplace Engineering has been received.

Thanks for the quick fix Anthony.
