### ISSUE TITLE
ancient logo packs for download

### ISSUE THREAD

**Issue by setharnold** [canonical/canonical.com#736]
Hello, https://canonical.com/press-centre has two logo packs available for download. They are apparently from 2014 using logos from 2010. It might be worth a refresh. :)

Thanks

**Comment by grebennikov** [comment]
Also https://design.ubuntu.com/downloads/ this contains quite outdated assets and the page footer says "2019"

**Comment by petesfrench** [comment]
@lyubomir-popov Any idea where I can find a more recent logo pack?

**Comment by lyubomir-popov** [comment]
Hi @petesfrench, The latest logos can be found on thew asset server (internal link) [link here ](https://assets.ubuntu.com/manager?tag=product-logos-2023)

**Comment by petesfrench** [comment]
@lyubomir-popov Is replacing the logos in the zip sufficient enough? It looks like there are a lot of other files that wont be found in the asset server such as ._ file and DS_store files

**Comment by petesfrench** [comment]
For whoever works on this, when you update the images on https://design.ubuntu.com/downloads/ you can update the footer to 2023, as advised by the legal team

**Comment by lyubomir-popov** [comment]
Hi @petesfrench the link above coontains all we have at the moment - we are working on a more full f ledged redesign of the design site, during which we'll identify any missing logos and add them.

**Comment by setharnold** [comment]
On Mon, Jan 09, 2023 at 05:50:52AM -0800, Peter French wrote:
> @lyubomir-popov Is replacing the logos in the zip sufficient enough? It
> looks like there are a lot of other files that wont be found in the
> asset server such as ._ file and DS_store files 

I'm pretty sure the ._ and DS_store files are Mac OS "hidden" files for
use with their file manager or previews or similar tools. Leaving those
out is probably an improvement.

Thanks

**Comment by carkod** [comment]
We shouldn't use Google Drive links, it's not accessible for the general public.

**Comment by egezeytun** [comment]
We have recently launched the new [canonical.com](http://canonical.com/). The press center page redirects the user to our publicly available Brand Drive. We had agreed that all logos and publicly accessible brand assets (such as Ubuntu wallpapers) will be stored in our Brand Drive, which is open to the public. The logos there are up-to-date.

**Comment by setharnold** [comment]
The new page looks sharp. Thanks for putting the assets up.
