### ISSUE TITLE
404 to some links

### ISSUE THREAD

**Issue by MikeeC** [canonical/canonical.com#767]
Both of the following URLs are 404:

https://canonical.com/careers/travel
https://canonical.com/careers/ethics

These are used in our candidate page so preferably resolved soon if possible.

Thanks!

**Comment by petesfrench** [comment]
@mtruj013 Could you take a look at this please?

**Comment by anthonydillon** [comment]
@MikeeC thank you for taking the time to report this issue. The pages are currently being reworked. We will remove the links for now.
