### ISSUE TITLE
candidate page has several dead links

### ISSUE THREAD

**Issue by StefanD986** [canonical/canonical.com#769]
# Steps to reproduce 
- On the candidate page `https://canonical.com/careers/application/${token}`, scroll down to the LIFE AT CANONICAL section
  - `${token}` is a personalized authentication token
- Click any of:
  - Ethics
  - Travel
  - Progression

# Actual behaviour
404: Page not found

# Expected behaviour
More information on any of the topics.

**Comment by mtruj013** [comment]
Thanks for reporting this @StefanD986. We've removed the links for now as these pages are undergoing redesign.
