### ISSUE TITLE
Career explorer returning `404: Page not found`

### ISSUE THREAD

**Issue by Benjamin-Loison** [canonical/canonical.com#771]
## Summary

The [`Career explorer`](https://canonical.com/careers/career-explorer) button on several webpages such as [`Engineering | Careers | Canonical`](https://canonical.com/careers/engineering) redirects to a `404: Page not found` webpage.

## Process

Go on [`Engineering | Careers | Canonical`](https://canonical.com/careers/engineering) and click on the [`Career explorer`](https://canonical.com/careers/career-explorer) button.

## Current and expected result

Found `404: Page not found` webpage while we would expect a webpage with content corresponding to a *career explorer*.

## Screenshot

![Screenshot from 2023-01-25 23-33-20](https://user-images.githubusercontent.com/12752145/214707088-4e9453b2-27e4-4e4f-9114-b39619002bbb.png)

![Screenshot from 2023-01-25 23-33-04](https://user-images.githubusercontent.com/12752145/214707101-5f373e05-22e3-4b24-a97b-e65feae60a2e.png)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

Note that the website [`mybrowser.fyi`](https://mybrowser.fyi/) that you recommend to go on seems to have became a suspicious ad website, as shown.

![Screenshot from 2023-01-25 23-35-33](https://user-images.githubusercontent.com/12752145/214707566-d9c1db3a-fb71-4148-9822-8acdfaaf9643.png)

So you should remove this website from the issue template.

**Comment by mtruj013** [comment]
Thanks for reporting this @Benjamin-Loison! This was fixed in #779, closing.
