### ISSUE TITLE
How to get started with dev server on windows?

### ISSUE THREAD

**Issue by sumanbiswas7** [canonical/canonical.com#793]
I am using windows I see I can't use `dotrun` to run canonical locally. Can someone provide some information regarding this?

Sorry, I am writing here as I am new to open source and don't know where else to write.
Please let me know if this is inappropriate I'll delete this Issue.

**Comment by anthonydillon** [comment]
Hi @sumanbiswas7 thanks for reaching out. `dotrun` is developed to support Linux and Mac at the moment. Would you feel comfortable running the site using WSL2?

**Comment by sumanbiswas7** [comment]
Hello @anthonydillon , Yeah sure!

**Comment by gajeshbhat** [comment]
@sumanbiswas7 Have you found any success getting this site to run successfully on your local WSL setup? Can you please close the issue if you have found the solution? Please do share the solution or helpful links if you got it working.
