### ISSUE TITLE
Application page: wrong job name if candidate is moved to a different role 

### ISSUE THREAD

**Issue by andesol** [canonical/canonical.com#798]
Opening this because we currently have the same issue in the hiring reminders.

An edge case, but consider this:

- Candidate applies online to a role
- Candidate is moved (internally) to another role (same application)
- Since the candidate page uses the job name as appears in the job post (whenever available), the page will keep referring to the first role: "Your application for...". The rest of the data (stages, interviews, etc.) should be correct.

**Comment by lizzochek** [comment]
Hey @andesol . I believe the current logic is to remove the application and open a new one if candidate is moved. Is this issue still relevant?

**Comment by andesol** [comment]
@lizzochek It's a problem I didn't see myself, I was just anticipating it because I saw it elsewhere. 

If the application id changes once the candidate is moved, then this wouldn't be a problem, indeed. Maybe @u-coskun can confirm whether that's what happens.

**Comment by u-coskun** [comment]
@andesol Hi, the application ID will NOT change if the candidate is transferred to a new role (so the old application is deleted). All information regarding the previous application will be moved to the new role and the only proof they were ever there will be in the activity feed. However, if the candidate is simply added to a new role, then that will create a new application, hence a new application ID.
We do not want to do the first option except in rare circumstances (the candidate was accidentally added to the wrong role, for example), so majority of cases will be the second option, which means the application IDs will be different.

**Comment by andesol** [comment]
Thanks @u-coskun! In that case this become more of an edge case, so I don't think it's worth keeping the issue open. Closing then
