### ISSUE TITLE
Top navigation covered by tab navigation

### ISSUE THREAD

**Issue by ru-fu** [canonical/canonical.com#803]
## Summary

On https://canonical.com/documentation , if you expand the top navigation and then scroll down to the tabs, the navigation on the tab covers the top menu.

## Screenshot

![image](https://user-images.githubusercontent.com/11227796/220287051-093d2536-d987-4ce8-a34c-e432675b7ef9.png)

## Browser details

Chrome

**Comment by petesfrench** [comment]
@ru-fu Thank you for reporting this issue
