### ISSUE TITLE
A tiny issue with a tag & pointer

### ISSUE THREAD

**Issue by minkyngkm** [canonical/canonical.com#807]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary
When hover over each card, it turns into a pointer, but when click on it, it doesn't go to the link.
Since the link works only on the text, either the mouse pointer works only over the text or `a` tag should wrap the entire card.

![ezgif com-crop](https://user-images.githubusercontent.com/57550290/220700524-f37e0a71-2217-4d9b-ada6-106c76482845.gif)

**Comment by anthonydillon** [comment]
This page has been redesigned.
