### ISSUE TITLE
Unable to submit my candidature: Error 413 Request Entity Too Large

### ISSUE THREAD

**Issue by carriba** [canonical/canonical.com#813]
Despite several retries, it seems I am unable to submit my candidature for your job posting with requisition ID 932. 

When having filled the fields under https://canonical.com/careers/4377100, and clicking on the "**Submit application**" button, I am getting a web page displayed with the message "Error 413 Request Entity Too Large".

From this error message I am not able to determine what might have gone wrong. Please, would you mind having a look.

**Comment by lizzochek** [comment]
Hello @carriba ! I am not able to reproduce the issue, but I believe it's most probably that the resume and/or CV file you added was too large. Currently we have functionality to check the files size here: https://github.com/canonical/canonical.com/blob/main/static/js/file-validation.js

Please try submitting again with a file size of max 1MB. If the issue persists for you, please reopen the issue

**Comment by lizzochek** [comment]
Hello @carriba ! I am not able to reproduce the issue, but I believe it's most probably that the resume and/or CV file you added was too large. Currently we have functionality to check the files size here: https://github.com/canonical/canonical.com/blob/main/static/js/file-validation.js

Please try submitting again with a file size of max 1MB. If the issue persists for you, please reopen the issue
