### ISSUE TITLE
Invalid Token - Candidate Page

### ISSUE THREAD

**Issue by sarahbrn2407** [canonical/canonical.com#814]
Hello,

I am a current applicant for a position at Canonical and I am unable to access my candidate page due to an invalid token. 

Please let me know how to include a screenshot in this type of tickets (if needed), as well as the information required to resolve the issue. 
I will provide them as soon as possible.

Thank you and kind regards,
Sarah

**Comment by carkod** [comment]
Please reach out to your hiring lead to get a new URL for the application page. Thanks
