### ISSUE TITLE
"Default issue" GitHub template includes link to defunct mybrowser.fyi

### ISSUE THREAD

**Issue by lathiat** [canonical/canonical.com#816]
The default GitHub issue template for this repository requests users submitting a bug to paste browser details using mybrowser.fyi.

The website mybrowser.fyi appears defunct. It has a 200+ day old expired SSL certificate and when loaded anyway it has a "buy this domain" landing page with some ads. The domain likely expired and was snapped up, it shows "Creation Date: 2021-09-09T17:09:46Z" in whois.

The template should be updated, note however it seems nto unlikely that we have this linked from issue templates in other repositories (not just canonical.com). Whoever fixes this should probably check our template for all repositories.

Reference:
https://github.com/canonical/canonical.com/issues/new?assignees=&labels=&template=ISSUE_TEMPLATE.md&title=

**Comment by britneywwc** [comment]
Thanks for flagging this! I've pushed up a PR that removed the broken link from the repo's default GH issue template.
