### ISSUE TITLE
Career Search: Searching for a new keyword unselects the Department/Location filters every time

### ISSUE THREAD

**Issue by lathiat** [canonical/canonical.com#818]
## Summary

If you enter/change the keywords in the "Search by keyword" input and submit the form, it erases the currently selected Departmant and Location filters.

This is confusing and makes it difficult for people to iterate through multiple keyword search in a specific relevant location.

## Process

1. Visit https://canonical.com/careers/all
2. Search for a keyword, e.g. "manager", and submit the form
3. Click a filter, e.g. "Location: APAC". Observe that the results list updates immediately, and that the query string in the URL now includes the original "search=manager" and the new "location=apac" together as https://canonical.com/careers/all?search=manager&location=apac
4. Change your keywords to "software engineer" and submit the form
5. Observe that the location=apac filter is dropped.

This appears to be because the keyword search and the filter list are two separate <form> elements on the page.

## Current and expected result

Current result: Department/Location filter selection is lost everytime you search for different keywords

Expected result: Changing the keywords, department filter or location filter in any order should always maintain the other selections

## Browser details

Chrome 111.0.5563.64 (Official Buidl) (arm64) - MacOS Ventura 13.2.1

**Comment by marinacastejon** [comment]
Hi @lathiat , thanks for raising this. I agree with your proposal, it makes sense to maintain the filters after a new query. We will be tracking the work in this internal[ issue in JIRA](https://warthogs.atlassian.net/browse/WD-2815).

**Comment by carkod** [comment]
Duplicate and fixed by https://github.com/canonical/canonical.com/pull/1155
