### ISSUE TITLE
Careers experience could be significantly improved, particularly around location filters

### ISSUE THREAD

**Issue by lathiat** [canonical/canonical.com#819]
## Summary

Currently using canonical.com/careers can be very confusing particularly if you want to keep a location selected, e.g. only roles in APAC. I think this could be significantly improved and I have tried to explain how and why in this issue.

This is a bit of a catch-all issue, it's very long.. but I am not sure how to distill my overall message down better, so first I will describe my context, then give a specific list of actions which give unexpected results and then a more generic explanation of how I feel the experience could be designed better.

I don't expect this issue to really remain open as is, I wanted to express my entire experience and feeling and then have someone in the team who understands the current intended design and also technical limitations to take this analysis and then split it out into specific actionable tasks depending on how my expectations interact with those factors. I did file two specific issues (linked in the list below) but once I got to ten separate items which may be cross-related or fixable at the same time, I didn't want to keep filing more individual items without a wider discussion first.

If you can give me some guidance I'm happy to do the work of splitting specific items into a separate bug.

## Context

As someone working from Australia in the APAC region, it is very common with other companies that job roles are advertised with locations that are not realistic. While Canonical is generally quite good at not doing this, myself and many I have talked to often experience that either:
- Jobs say "Worldwide" when they really mean America + EMEA
- The number of relevant jobs in APAC or Australia is typically much smaller than the total pool.

As a result it is critical when apply from APAC/Australia to ensure we always filter by location. Firstly we don't want to see what is often an overwhelmingly large list of jobs not for our region (even if they are tagged correctly), and secondly specifically filtering for APAC or Australia will often remove the jobs that may not apply to us - even if they otherwise claim to allow working from "anywhere" but really mean Americas+EMEA.

Generally Canonical is great at correctly listing the location and meaning Worldwide when it says so, but we still need to remove the large list of jobs we do have which are correctly tagged as region specific. Particularly in departments like Engineering or Support Engineering that have 40-100+ roles and the list is otherwise overwhelmed by non-relevant jobs (e.g. only 57/114 Engineering roles apply to APAC).

## Specific list of actions which produce unexpected or unhelpful results

I have tried to distill my experience into a list of why with actionable suggestions on how this could be improved.

Location specific

1. The landing page at https://canonical.com/careers has a search field but no location filter. The only way to filter on location is to submit the form, then a location filter appears. However when you type a search you get an autocompleted list of jobs that you can click which goes directly to the job opening with no further search context (including location). Users using the form in this way may have no idea the location option exists.
2. When using the autocomplete "mode" of the job search, it lists locations in the autocomplete results (e.g. Home Based - APAC). However the search doesn't actually match the words in the location shown, a search for "APAC" incorrectly matches 2 jobs that happen to have APAC in their Job Title (most don't) and worldwide has 0 matches. This is filed separately as https://github.com/canonical/canonical.com/issues/817
3. When using the /careers/all search, the Location and Department filters are lost anytime you change the keyword search. I filed this separately at https://github.com/canonical/canonical.com/issues/818
4. Starting from /careers/all, if you set a Department or Location filter, then click a job, then "Back to list", the filters are often reset to the values in the job you had clicked. If you started with an APAC filter and clicked a "Worldwide" job, now you have no Location filter. If you had selected 3 Departments, click a job from one, then click back to list then only the department of the job you had selected is clicked. It seems that some jobs have a location that is not in the filter list - one job gave me "location=oceania" in the query string after clicking back to list (normally its location=apac). Most of the time I go back to a filter of the department of the job I viewed, but some jobs seem to leave you with no Department selected but another time I randomly ended up back with a list of 3 departments that I had set some 10+ jobs ago all while using the same tab. So while it shouldn't be changing the filters to match the job I clicked, sometimes it seems to get a list from somewhere else and I am not sure why.

Career Explorer

6. If you start with the Career Explorer, once submitted the [results page](https://canonical.com/careers/results?core-skills=Tester,Teacher,Analyzer,Organiser,Helper) features a Location filter (no department filter) but it does not appear to work. It does not live-update the page and that location context is lost if you click any links.
7. From the Career Explorer results page, you are limited to 9 jobs per department and there is no possible way to get a full list of "for you" jobs or carry the "for you" context into the full search experience. You can only (through 2 extra clicks) get a full list of jobs in each matching department. For large varied Departments like Engineering, this misses the opportunity to showcase the full list of sub-roles that match them.
8. Both the department name (e.g. "Engineering") and the "See all roles in Engineering" link take you to the [department landing page](https://canonical.com/careers/engineering). This page shows only 6 different "Featured" roles which do not take any relevant context into account. You then need to click the link that says "See all Engineering roles" which is almost but not quite the same as the "Sell all roles in Engineering" link to get to the actual search experience.

[Department Landing Page](https://canonical.com/careers/engineering)

9. Both canonical.com/careers clicking on a Department name, and the "Career Explorer" when both clicking on a department name _OR_ "See all roles in Engineering" take you to the Department Landing page. On my 1440p high screen, more than 2/3rds of the screen is taken up by this incomplete list of featured roles - and the unique content of this page (a long written page on what it's like to work in that department) can easily be missed as it is mostly off-screen. As a result, it feels like an unhelpful extra click gateway to the proper search results page. Screenshot included at the bottom of the issue.

Other

10. When you click right into a job ad, you cannot see the department that job is in and there is no link or way to look at other jobs in that department or otherwise similar. Clicking "Back to list" does different things depending on the context you came from (career explorer, a filtered search, clicking a job in the autocomplete keyword search list). Often, you go back to the full complete job search list with no filtering selected. However as mentioned in Item 4 sometimes you do get your Location and/or Department set to match the job you were in - but not always - so this is no substitute for the lack of a listed department on the job page.

## Guiding principles for a possibly better design

In the above list I described various specific ways that the current site operates in ways that I do not expect or are confusing, particularly with respect to Location, some of them can be solved independently (and I filed some of those as separate bugs, linked above), but I think the following guiding principles would describe a fix to almost all of those issues.

1. First, my guiding principal experience is that I am likely to be one of two applicant types. This may be a bad assumption I am making, and may make my following suggestions invalid
    a. A detail oriented applicant, I would want to feel like I had viewed a "complete" list of all jobs that may have applied to me to make a decision of which to choose before applying. That complete list may be based on the career explorer, based on a keyword search, based on a location search, or some combination of those. I would narrow the search down in some way and have viewed all matching jobs before then choosing one to submit against. 
    b. We sometimes had talked about putting applicants into a more generic pipeline perhaps as "Python Software Engineer" and we would then help direct them into specific teams later. I'm not sure if we still try to do that, and that feels like a useful pipeline especially since the above "detail oriented applicant" probably does not apply to every kind of applicant. However it's not clear to me how we currently allow people to apply into such a pipeline. You still seem to have to select a specific team and role. So I am not sure we really cater to that now.
2. When you select any filter, but especially location, I would expect that context to persist through any change including moving between all roles and career explorer, changing department filter, changing the keyword, etc. The Location context should never be lost unless explicitly de-selected.
3. Right now many of the experiences show you an arbitrarily limited incomplete list of job possibilities - specifically the career explorer shows you a maximum of 9 per department (with no functional location filter) before directing you to click to view "all" roles in that department. Once you click that department landing page, it now only shows you 6 "Feature roles" unrelated to your career explorer results with a further click needed to get into the job search which then has no way to show every role that matched your career explorer results.

One possible experience to solve these would be to drive the entire /careers section inside of a search context. It starts blank, then, if you select a location filter, that is maintained and never lost. If you use the career explorer, it will remember the results of those in a cookie and let you select or unselect a "Jobs for you" option that would narrow the list only to those matching or let you click to remove and re-add that limitation, etc.

## Screenshots

Photo of the design of the department landing page which almost entirely hides the unique content mentioned in Item 2
![Screenshot 2023-03-17 at 1 48 34 pm](https://user-images.githubusercontent.com/290673/225823210-ef2accf4-c64e-412c-97b7-6c43007b5b7a.png)

## Browser

Chrome 111.0.5563.64 (Official Buidl) (arm64) - MacOS Ventura 13.2.1

Resolution: Single ultra-wide 3440x1440

**Comment by carkod** [comment]
Improved by https://github.com/canonical/canonical.com/pull/1150
