### ISSUE TITLE
Search of open roles misses some of them

### ISSUE THREAD

**Issue by KonstantNY** [canonical/canonical.com#827]
How to check:
1. Open the link: https://canonical.com/careers/all
2. Type "QA" in the search field.
3. Remember the result, i.e. number of roles with "QA" in their names (for 2023-03-07 yyyy/mm/dd) I found only one (see screenshot attached): "Linux System Engineer - QA, Tooling, Automation"
4. Look through all the open roles with "Engineering" and "Support Engineering" check boxes selected. I found one more position (see screenshot attached): Software Engineer, Integration QA, Python.

![1_QA-search-result](https://user-images.githubusercontent.com/19522031/227984935-50b18cfe-9dd1-444b-9df6-55b00f07d7f0.PNG)
![2 0_QA-looking-through-the-list-of-opened-positions](https://user-images.githubusercontent.com/19522031/227984967-303fd4a4-c3e8-4cee-8799-cf28a5412a82.PNG)
![2 1_QA-looking-through-the-list-of-opened-positions](https://user-images.githubusercontent.com/19522031/227984976-4eed5ca0-eb1d-4674-9732-b28028108c1d.PNG)

**Comment by lizzochek** [comment]
Hello @KonstantNY, thank you for filing an issue. This problem has been addressed
