### ISSUE TITLE
Livestyle and remote work - visual glitches

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/canonical.com#831]
There are a few small issues in the implementation of his page:

- header differs from the design:
design:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/2741678/230135856-4f1b35a9-7068-4529-8a08-31214389546a.png">

implementation:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/2741678/230135923-570e6936-33a4-4483-a893-d7c696ba99c1.png">

- missing hr

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/2741678/230136139-bed1d3a6-d96e-40ae-94bf-655e1b13adf1.png">

- map out of sync with rest of grid width 
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/2741678/230136273-c7beb7ba-3b07-4a40-9ca7-574877e548ab.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/2741678/230136332-e91e729b-969f-48f9-8d3c-01ab79437335.png">

wrong aspect ratio (should be 3x2):
<img width="715" alt="image" src="https://user-images.githubusercontent.com/2741678/230136429-6f7ef341-6759-461a-a569-c963e55499f4.png">

**Comment by carkod** [comment]
I believe this is fixed? Reopen if necessary
