### ISSUE TITLE
Unable to access candidate page at canonical 

### ISSUE THREAD

**Issue by alimshaikh1** [canonical/canonical.com#833]
I am unable to access my candidate page at canonical and it shows the following message
![Screenshot 2023-04-11 130952](https://user-images.githubusercontent.com/129205074/231129376-033ac5b5-7047-4a01-be74-fe0cb100e26e.png)

**Comment by carkod** [comment]
Please, can you reach out to your hiring lead? This doesn't look like an error that happens consistently to all candidates
