### ISSUE TITLE
p-strip sets background to white

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/canonical.com#834]
![image](https://user-images.githubusercontent.com/2741678/231141018-a5b43de7-01f7-4b10-a077-1c5be266d44c.png)

We are about to add the new "paper" colour proposed by PU, and @bartaz is thinking of doing that on the `body`. In vanilla, regular strips set background to transparent. For some reason, on canonical.com that has been overriden to white. Ca nyou please investigate when that was added, and if it is needed - limit it to wherever it was introduced?

**Comment by anthonydillon** [comment]
This has been resolved.
