### ISSUE TITLE
Navigation drop-downs missing a line-break between the last two items

### ISSUE THREAD

**Issue by petesfrench** [canonical/canonical.com#835]
![image](https://user-images.githubusercontent.com/58276363/231994283-4e63ca54-941a-405a-8d1c-3c7e0a807141.png)
![image](https://user-images.githubusercontent.com/58276363/231994348-1639ff60-75e6-43cf-9142-e45da3161e0f.png)

**Comment by anthonydillon** [comment]
This seems to be resolved.
