### ISSUE TITLE
Accessing the candidate page returns 500

### ISSUE THREAD

**Issue by gaganso** [canonical/canonical.com#838]
I tried accessing my candidate page and got a 500: server error. I reviewed the related bugs, and this is the [closest](https://github.com/canonical/canonical.com/issues/755). However, my link does have an encrypted code (not posting here for security reasons). Please find the error page below:
<img width="1506" alt="Screenshot 2023-04-16 at 9 01 15 PM" src="https://user-images.githubusercontent.com/27358592/232338974-4eb6be3a-d688-4d0f-8d0a-faed65b78262.png">

**Comment by cobras** [comment]
Same for me. I have the same error

**Comment by jetunp** [comment]
Facing the same issue.

**Comment by codergan** [comment]
Same here

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue to us. I have looked into the issues and it appears Greenhouse API had an outage for around 8 hours yesterday. This has been rectified. Can you try again and let me know if this issue is persistent?
