### ISSUE TITLE
one of the stock images we use is not related to tech

### ISSUE THREAD

**Issue by anasereijo** [canonical/canonical.com#844]
On the 'Explore diverse roles' section, we display an image containing fabric samples. In my opinion, this should be replaced with something more generic or tech related.

<img width="383" alt="Screenshot 2023-04-20 at 15 26 58" src="https://user-images.githubusercontent.com/36884067/233397648-89c0dd3d-07ca-42f5-aa9f-2b0a5549f465.png">

Also, seems that all the laptops in the photographs are Macs, maybe we could at least photoshop the logo out? - just a suggestion

BTW the website looks super nice! Well done everyone!

**Comment by carkod** [comment]
This should be fixed by now.
