### ISSUE TITLE
"Diversity" is not aligned in the dropdown

### ISSUE THREAD

**Issue by elenapalombini** [canonical/canonical.com#849]
The text "Diversity" is not aligned to the other options in the Careers dropdown menu.

<img width="172" alt="Screenshot 2023-04-29 at 23 50 32" src="https://user-images.githubusercontent.com/38339338/235327235-ea6eea4e-d2b5-454e-bd99-83e4ee700635.png">

**Comment by carkod** [comment]
If you look at the partners drop down, when the text is indented it means it is a child page. See attached <img width="1036" alt="Screenshot 2023-05-05 at 15 36 14" src="https://user-images.githubusercontent.com/14939793/236488647-d5e8f2ba-bbcf-45dd-ad99-64c8789227a8.png">
