### ISSUE TITLE
Favicon is showing old logo

### ISSUE THREAD

**Issue by bartaz** [canonical/canonical.com#861]
## Summary

Website is using new logo, but favicon is still showing old purple circle:

<img width="465" alt="image" src="https://github.com/canonical/canonical.com/assets/83575/7fc37a2e-2d5a-4d10-bcc4-41f4c2a12c37">

**Comment by LefterisXefteris** [comment]
I am trying to get into the https://assets.ubuntu.com/v1/ , however, i get ""{
    "code": 401,
    "message": "401 Unauthorized: Invalid or missing token."
}.. is there any chance i get the token, so i can access and update the favicon?

**Comment by bartaz** [comment]
Thanks for reaching out @LefterisXefteris.

Assets server is for our internal use, so we can't give you access, unfortunately.

Canonical.com is being redesigned right now and new version will be published soon, so the favicon issue will be resolved then.

Thanks!

**Comment by anthonydillon** [comment]
This has need resolved.
