### ISSUE TITLE
Careers filter of department and location is not working

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#870]
This link is not working correctly:
https://canonical.com/careers/all?filter=Web+%26+Design&location=americas

**Comment by LefterisXefteris** [comment]
i Would love to fix this since the issue is not closed. could you specify what is wrong?

**Comment by carkod** [comment]
I think the filter rmoved the location

**Comment by lathiat** [comment]
Can we get this fixed? It's very difficult to search for APAC roles.

**Comment by carkod** [comment]
Fixed by https://github.com/canonical/canonical.com/pull/1155
