### ISSUE TITLE
Unable to run the dotrun snap to run the site locally

### ISSUE THREAD

**Issue by Jim-Dillon** [canonical/canonical.com#881]
## Summary

Hi all, I'm trying to open the project locally and I'm having an issue with running the dotrun snap. My OS is macOS Ventura 13.4.

## Process

I've followed the instructions from the READMEs: 

- Install and run Docker 
- Install Homebrew 
- Run the two commands under the [Mac](https://github.com/canonical/dotrun/blob/main/README.md) section of the Dotrun README

Then finally when I run the `dotrun` command from the [Canonical.com README](https://github.com/canonical/canonical.com/blob/main/README.md), I get the following error:

"Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'"
"Dotrun needs Docker to work, please check if Docker is installed and running"

My Docker is installed and running so I assume the issue is stemming from the first line. I'm wondering if anyone has encountered this issue before and can spot an oversight from myself at all. 

Thank you!

**Comment by bartaz** [comment]
Moved to dotrun, closing as duplicate: https://github.com/canonical/canonical.com/issues/881

**Comment by carkod** [comment]
@bartaz did you mean to close this issue?
