### ISSUE TITLE
Diversity tab on Careers menu is misaligned

### ISSUE THREAD

**Issue by gajeshbhat** [canonical/canonical.com#883]
<img width="1440" alt="Canonical Diversity tab Misalignment" src="https://github.com/canonical/canonical.com/assets/16153045/9690c599-6230-4d66-bb96-953b21874352">
The Diversity tab in the Careers menu needs to be aligned with other entries in the Careers menu.

**Comment by andesol** [comment]
I think this has to do with the fact that "Diversity" is a sub-category of "Company culture", hence the indentation. It looks less confusing now that there is a second item nested. 

![image](https://github.com/canonical/canonical.com/assets/20623084/4bb1e01a-8706-49ba-b265-94cb052bb038)

**Comment by gajeshbhat** [comment]
It makes sense now. Regards.
