### ISSUE TITLE
404: Page not found

### ISSUE THREAD

**Issue by africangay** [canonical/canonical.com#885]
https://canonical.com/enterprise-services/ubuntu-advantage

404: Page not found
Sorry, we can't find the page you're looking for.

If you think this is an error on our site, please [file a bug](https://github.com/canonical-web-and-design/canonical.com/issues/new).

**Comment by anthonydillon** [comment]
Thanks for reporting this issue. We should add the following redirect:
```
enterprise-services/ubuntu-advantage?: "https://ubuntu.com/pro"
```

@egezeytun can we add this to Jira and assign it to this pulse as a  small task, please?
