### ISSUE TITLE
Text wrapping issue on home page

### ISSUE THREAD

**Issue by andrewjamessinclair** [canonical/canonical.com#970]
## Summary

The text wrapping on at least of the headers on the updated home page behaves unexpected: it eliminates a necessary space when that page is viewed on a narrow window such as a phone.

## Process

Go to canonical.com, narrow browser, view the heading "Optimised for IoT and edge"

## Current and expected result

Current result looks like: "Optimisedfor IoT and edge"

Expected result would look like: "Optimised for IoT and edge"

## Screenshot

I have this, but don't see a way to attach it.

## Browser details

Chrome on Mac. Safari on iPhone.

**Comment by carkod** [comment]
This is fixed with the new page.
