### ISSUE TITLE
clicking on 'See all Web & Design roles' doesn't take users to a filtered page

### ISSUE THREAD

**Issue by anasereijo** [canonical/canonical.com#973]
/web-and-design if we click on 'See all Web & Design roles' it will take to a page with no filters selected, even though the url seems to be correct (https://canonical.com/careers/all?filter=Web%20&%20Design)

https://github.com/canonical/canonical.com/assets/36884067/15ad29c9-4ff7-44ed-bf63-79f78fcfd9c5

**Comment by carkod** [comment]
This has been fixed https://github.com/canonical/canonical.com/pull/932
