### ISSUE TITLE
Careers search is too strict

### ISSUE THREAD

**Issue by clinton-fung** [canonical/canonical.com#981]
The search functionality on https://canonical.com/careers does not return results that should be returned.

### Setup
Given two roles with the following titles:
- Software Engineer - Ubuntu Build Infrastructure
- Software Engineering Manager - Ubuntu Build Infrastructure

### Steps to reproduce
1. Visit https://canonical.com/careers
2. Type "ubuntu", "build", "infrastructure", "ubuntu build", "build infrastructure", or "ubuntu build infrastructure" into the search box
3. Select "Search roles"

### Expected behaviour
- Search results for the provided search term are displayed.
- Both the roles listed in the "Setup" section are part of the search results.

### Actual behaviour
- Search results for the provided search term are displayed.
- Only one role is part of the search results.

### Additional notes
- Investigation highlighted that `fuse.js` is used for the search, and it checks `title`. `description`, `departments`, and `skills` fields, with `threshold = 0.3`.
- In a prototype, I've tested that `threshold = 0.7` returns the results that were previously missing, but of course there are many more other results that are also returned.
- One suggestion is to use the `ignoreLocation` parameter with e.g. `ignoreLocation = true`, so that the entire text is eligible for search
- Another suggestion is to update `threshold = 0.7`.
- Yet another suggestion is to add tags functionality that can be used for searching
- A final suggestion is to create a list of all words in both the title and description, remove certain common words that shouldn't be searchable ("the", "in", "and", etc), and then add this list to the searchable keys.

**Comment by leeoniya** [comment]
> A final suggestion is to create a list of all words in both the title and description, remove certain common words that shouldn't be searchable ("the", "in", "and", etc), and then add this list to the searchable keys.

shameless plug: https://github.com/leeoniya/uFuzzy
related: https://github.com/leeoniya/uFuzzy/issues/7
