### ISSUE TITLE
post from ubuntu.com/blog shows no summary on Google search results

### ISSUE THREAD

**Issue by jugmac00** [canonical/canonical.com#987]
## Summary

Today I googled for "openstack sunbeam" and the second result was one of https://ubuntu.com/blog/canonical-extends-commercial-openstack-offering-to-small-scale-cloud-environments-with-project-sunbeam, but Google only showed the title, but no summary.

## Process

Probably google for "openstack sunbeam".

## Current and expected result
Currently, no summary is shown, but I expect to see one.

## Screenshot
![Screenshot from 2023-07-26 11-58-01](https://github.com/canonical/canonical.com/assets/9895620/4af2258f-89d0-46f7-9d13-39ab2f545cf1)

## Browser details
The issue is browser-independent.

**Comment by carkod** [comment]
We had some issues with crawling that now have been fixed, so this should be working now

**Comment by jugmac00** [comment]
Thanks for fixing! 👍
