### ISSUE TITLE
Cannot select my strength on the career-explorer page

### ISSUE THREAD

**Issue by megametres** [canonical/canonical.com#998]
Hello,
When opening the page https://canonical.com/careers/career-explorer, I cannot select my strengths and there is this error in the javascript console:
`TypeError: a.default.detectStore(...) is undefine [h1-check.js:1:1301`
![image](https://github.com/canonical/canonical.com/assets/2496407/0f35dd96-8047-4dfd-8aa1-15772f41907a)

Here is my user agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue to us. I cannot seem to replicate it on Firefox 114. Could you check if it's not a browser extension? If you still see it can you reopen this issue, please?

**Comment by megametres** [comment]
Hello,

I disabled all extensions and I still reproduce the issue that I cannot select my strength but with a different error...
![image](https://github.com/canonical/canonical.com/assets/2496407/75e907dc-2960-42b3-90d3-76204c8e60c6)
